-- OIDC identity links for SSO login (see schema/25 - UserOidcIdentities.sql)
CREATE TABLE IF NOT EXISTS public."UserOidcIdentities"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "Provider" text COLLATE pg_catalog."default" NOT NULL,
    "Subject" text COLLATE pg_catalog."default" NOT NULL,
    "Email" text COLLATE pg_catalog."default",
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_UserOidcIdentities" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_UserOidcIdentities_Provider_Subject" UNIQUE ("Provider", "Subject"),
    CONSTRAINT "FK_UserOidcIdentities_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_UserOidcIdentities_UserId"
    ON public."UserOidcIdentities" ("UserId");
