-- Rating engine persistence (see schema/26 - Ratings.sql, 27 - RatingHistory.sql)
CREATE TABLE IF NOT EXISTS public."Ratings"
(
    "UserId" integer NOT NULL,
    "Pool" text NOT NULL,
    "Rating" integer NOT NULL,
    "GamesPlayed" integer NOT NULL DEFAULT 0,
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Ratings" PRIMARY KEY ("UserId", "Pool"),
    CONSTRAINT "FK_Ratings_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Ratings_Pool_Rating"
    ON public."Ratings" ("Pool", "Rating" DESC);

CREATE TABLE IF NOT EXISTS public."RatingHistory"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "GameId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "OpponentId" integer NOT NULL,
    "Pool" text NOT NULL,
    "Won" boolean NOT NULL,
    "RatingBefore" integer NOT NULL,
    "RatingAfter" integer NOT NULL,
    "Expected" real,
    "OwnSas" integer,
    "OpponentSas" integer,
    "KeyDiff" integer,
    "ResultType" text,
    "ConfigSnapshot" jsonb,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_RatingHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_RatingHistory_Game_User" UNIQUE ("GameId", "UserId"),
    CONSTRAINT "FK_RatingHistory_Games_GameId" FOREIGN KEY ("GameId")
        REFERENCES public."Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RatingHistory_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_RatingHistory_UserId_Pool"
    ON public."RatingHistory" ("UserId", "Pool", "Id" DESC);
