-- Tournament engine (see schema/30-32)
CREATE TABLE IF NOT EXISTS public."Tournaments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text NOT NULL,
    "Description" text,
    "OrganizerId" integer NOT NULL,
    "Format" text NOT NULL,
    "GameFormat" text NOT NULL DEFAULT 'archon',
    "Mode" text NOT NULL DEFAULT 'online',
    "Status" text NOT NULL DEFAULT 'registration',
    "RoundCount" integer,
    "CurrentRound" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp without time zone NOT NULL,
    "StartedAt" timestamp without time zone,
    "FinishedAt" timestamp without time zone,
    CONSTRAINT "PK_Tournaments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tournaments_Users_OrganizerId" FOREIGN KEY ("OrganizerId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Tournaments_Status"
    ON public."Tournaments" ("Status", "Id" DESC);

CREATE TABLE IF NOT EXISTS public."TournamentPlayers"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TournamentId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Dropped" boolean NOT NULL DEFAULT false,
    "Seed" integer,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TournamentPlayers" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_TournamentPlayers_Tournament_User" UNIQUE ("TournamentId", "UserId"),
    CONSTRAINT "FK_TournamentPlayers_Tournaments" FOREIGN KEY ("TournamentId")
        REFERENCES public."Tournaments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentPlayers_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."TournamentMatches"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TournamentId" integer NOT NULL,
    "Round" integer NOT NULL,
    "TableNumber" integer,
    "Player1Id" integer NOT NULL,
    "Player2Id" integer,
    "WinnerId" integer,
    "ReportedBy" integer,
    "ReportedAt" timestamp without time zone,
    CONSTRAINT "PK_TournamentMatches" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TournamentMatches_Tournaments" FOREIGN KEY ("TournamentId")
        REFERENCES public."Tournaments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentMatches_Player1" FOREIGN KEY ("Player1Id")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentMatches_Player2" FOREIGN KEY ("Player2Id")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_TournamentMatches_Tournament_Round"
    ON public."TournamentMatches" ("TournamentId", "Round");
