-- Community features: friends + clubs (see schema/33-35)
CREATE TABLE IF NOT EXISTS public."Friendships"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "RequesterId" integer NOT NULL,
    "AddresseeId" integer NOT NULL,
    "Status" text NOT NULL DEFAULT 'pending',
    "CreatedAt" timestamp without time zone NOT NULL,
    "RespondedAt" timestamp without time zone,
    CONSTRAINT "PK_Friendships" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_Friendships_Pair" UNIQUE ("RequesterId", "AddresseeId"),
    CONSTRAINT "CK_Friendships_NotSelf" CHECK ("RequesterId" <> "AddresseeId"),
    CONSTRAINT "FK_Friendships_Requester" FOREIGN KEY ("RequesterId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Friendships_Addressee" FOREIGN KEY ("AddresseeId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Friendships_Addressee"
    ON public."Friendships" ("AddresseeId");

CREATE TABLE IF NOT EXISTS public."Clubs"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text NOT NULL,
    "Description" text,
    "OwnerId" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Clubs" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_Clubs_Name" UNIQUE ("Name"),
    CONSTRAINT "FK_Clubs_Users_OwnerId" FOREIGN KEY ("OwnerId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."ClubMembers"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ClubId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Role" text NOT NULL DEFAULT 'member',
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ClubMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_ClubMembers_Club_User" UNIQUE ("ClubId", "UserId"),
    CONSTRAINT "FK_ClubMembers_Clubs" FOREIGN KEY ("ClubId")
        REFERENCES public."Clubs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ClubMembers_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_ClubMembers_UserId"
    ON public."ClubMembers" ("UserId");
