-- Local game stores / venues for in-person play (Phase 9, Play IRL).

CREATE TABLE IF NOT EXISTS public."Stores"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Country" text COLLATE pg_catalog."default",
    "State" text COLLATE pg_catalog."default",
    "City" text COLLATE pg_catalog."default",
    "Address" text COLLATE pg_catalog."default",
    "Website" text COLLATE pg_catalog."default",
    "Description" text COLLATE pg_catalog."default",
    "AddedByUserId" integer,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Stores" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Stores_Users_AddedByUserId" FOREIGN KEY ("AddedByUserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_Stores_Country_State"
    ON public."Stores" ("Country", "State");
