-- Tournament engine v2 (Phase 7 increments 2-4): scheduling, check-in,
-- caps + waitlists, private events, staff, deck registration with SAS
-- bounds, best-of series, double elimination / round robin / Swiss cut
-- brackets, round timers, penalties, rated games, final placements and
-- online game automation. See docs/design/tournament-engine.md.

ALTER TABLE public."Tournaments"
    ADD COLUMN IF NOT EXISTS "StartTime" timestamp without time zone,
    ADD COLUMN IF NOT EXISTS "PlayerCap" integer,
    ADD COLUMN IF NOT EXISTS "BestOf" integer NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS "PlayoffBestOf" integer,
    ADD COLUMN IF NOT EXISTS "CutTo" integer,
    ADD COLUMN IF NOT EXISTS "Stage" text NOT NULL DEFAULT 'main',
    ADD COLUMN IF NOT EXISTS "SeedMethod" text NOT NULL DEFAULT 'registration',
    ADD COLUMN IF NOT EXISTS "Visibility" text NOT NULL DEFAULT 'public',
    ADD COLUMN IF NOT EXISTS "JoinCode" text,
    ADD COLUMN IF NOT EXISTS "RoundTimerMinutes" integer,
    ADD COLUMN IF NOT EXISTS "RoundStartedAt" timestamp without time zone,
    ADD COLUMN IF NOT EXISTS "CheckInOpenedAt" timestamp without time zone,
    ADD COLUMN IF NOT EXISTS "RatedGames" boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "RequireDeckRegistration" boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "SasMin" integer,
    ADD COLUMN IF NOT EXISTS "SasMax" integer,
    ADD COLUMN IF NOT EXISTS "HideDecklists" boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "GameTimeLimit" integer,
    ADD COLUMN IF NOT EXISTS "Announcement" text;

ALTER TABLE public."TournamentPlayers"
    ADD COLUMN IF NOT EXISTS "DeckId" integer,
    ADD COLUMN IF NOT EXISTS "CheckedIn" boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "Waitlisted" boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "FinalRank" integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'FK_TournamentPlayers_Decks' AND table_name = 'TournamentPlayers'
    ) THEN
        ALTER TABLE public."TournamentPlayers"
            ADD CONSTRAINT "FK_TournamentPlayers_Decks" FOREIGN KEY ("DeckId")
                REFERENCES public."Decks" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

-- Elimination bracket slots are created before their players are known,
-- so Player1Id becomes nullable; source references say which earlier
-- match feeds each slot.
ALTER TABLE public."TournamentMatches"
    ALTER COLUMN "Player1Id" DROP NOT NULL;

ALTER TABLE public."TournamentMatches"
    ADD COLUMN IF NOT EXISTS "Bracket" text,
    ADD COLUMN IF NOT EXISTS "BracketRound" integer,
    ADD COLUMN IF NOT EXISTS "BracketPos" integer,
    ADD COLUMN IF NOT EXISTS "P1SourceMatchId" integer,
    ADD COLUMN IF NOT EXISTS "P1SourceIsLoser" boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "P2SourceMatchId" integer,
    ADD COLUMN IF NOT EXISTS "P2SourceIsLoser" boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "Player1Wins" integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "Player2Wins" integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "BestOf" integer NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS "ResultType" text;

-- Byes recorded before v2 carried a winner but no result type.
UPDATE public."TournamentMatches"
    SET "ResultType" = CASE WHEN "Player2Id" IS NULL THEN 'bye' ELSE 'played' END
    WHERE "WinnerId" IS NOT NULL AND "ResultType" IS NULL;

-- Co-organizers / judges: full event management short of deletion.
CREATE TABLE IF NOT EXISTS public."TournamentStaff"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TournamentId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Role" text NOT NULL DEFAULT 'judge',
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TournamentStaff" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_TournamentStaff_Tournament_User" UNIQUE ("TournamentId", "UserId"),
    CONSTRAINT "FK_TournamentStaff_Tournaments" FOREIGN KEY ("TournamentId")
        REFERENCES public."Tournaments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentStaff_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

-- Links auto-created lobby games (and their results) to series games of
-- a tournament match; the unique game number makes auto-reporting
-- idempotent.
CREATE TABLE IF NOT EXISTS public."TournamentMatchGames"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TournamentId" integer NOT NULL,
    "MatchId" integer NOT NULL,
    "GameNumber" integer NOT NULL,
    "GameUuid" text NOT NULL,
    "WinnerId" integer,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TournamentMatchGames" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_TournamentMatchGames_Match_Number" UNIQUE ("MatchId", "GameNumber"),
    CONSTRAINT "FK_TournamentMatchGames_Tournaments" FOREIGN KEY ("TournamentId")
        REFERENCES public."Tournaments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentMatchGames_Matches" FOREIGN KEY ("MatchId")
        REFERENCES public."TournamentMatches" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_TournamentMatchGames_GameUuid"
    ON public."TournamentMatchGames" ("GameUuid");

CREATE INDEX IF NOT EXISTS "IX_Tournaments_Visibility"
    ON public."Tournaments" ("Visibility", "Status", "Id" DESC);

CREATE INDEX IF NOT EXISTS "IX_TournamentPlayers_User"
    ON public."TournamentPlayers" ("UserId");
