-- KeyForge-specific tournament conditions (Phase 7 increment 5):
-- deck swap policy, set legality, house restrictions, SAS chain
-- handicap, Chainbound-style event chains, and the official Triad
-- format (3-deck pools with per-match ban/pick).
-- See docs/design/tournament-engine.md.

ALTER TABLE public."Tournaments"
    ADD COLUMN IF NOT EXISTS "DeckSwapPolicy" text NOT NULL DEFAULT 'locked',
    ADD COLUMN IF NOT EXISTS "AllowedSets" jsonb,
    ADD COLUMN IF NOT EXISTS "RequiredHouses" jsonb,
    ADD COLUMN IF NOT EXISTS "BannedHouses" jsonb,
    ADD COLUMN IF NOT EXISTS "SasChainHandicap" boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "ChainsPerMatchWin" integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "Triad" boolean NOT NULL DEFAULT false;

ALTER TABLE public."TournamentPlayers"
    ADD COLUMN IF NOT EXISTS "EventChains" integer NOT NULL DEFAULT 0;

-- Triad state per match: which deck of each player's pool the opponent
-- banned, and which deck each player chose to pilot.
ALTER TABLE public."TournamentMatches"
    ADD COLUMN IF NOT EXISTS "P1BannedDeckId" integer,
    ADD COLUMN IF NOT EXISTS "P2BannedDeckId" integer,
    ADD COLUMN IF NOT EXISTS "P1DeckId" integer,
    ADD COLUMN IF NOT EXISTS "P2DeckId" integer;

-- Triad deck pools: exactly three decks per player, slot 1-3.
CREATE TABLE IF NOT EXISTS public."TournamentPlayerDecks"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TournamentId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "DeckId" integer NOT NULL,
    "Slot" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TournamentPlayerDecks" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_TournamentPlayerDecks_Slot" UNIQUE ("TournamentId", "UserId", "Slot"),
    CONSTRAINT "FK_TournamentPlayerDecks_Tournaments" FOREIGN KEY ("TournamentId")
        REFERENCES public."Tournaments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentPlayerDecks_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentPlayerDecks_Decks" FOREIGN KEY ("DeckId")
        REFERENCES public."Decks" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_TournamentPlayerDecks_Tournament"
    ON public."TournamentPlayerDecks" ("TournamentId", "UserId");
