-- Beta bug reports: sidebar "Report a Bug" submissions, read and
-- resolved from the admin panel (see schema/42).

CREATE TABLE IF NOT EXISTS public."BugReports"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer,
    "Page" text,
    "Body" text NOT NULL,
    "UserAgent" text,
    "Status" text NOT NULL DEFAULT 'open',
    "ResolvedBy" integer,
    "ResolvedAt" timestamp without time zone,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_BugReports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BugReports_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_BugReports_ResolvedBy" FOREIGN KEY ("ResolvedBy")
        REFERENCES public."Users" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_BugReports_Status"
    ON public."BugReports" ("Status", "Id" DESC);
