-- Rating decay + competitive seasons.
--
-- Track how far inactive-player rating decay has been applied per rating row
-- (so decay is idempotent), and record competitive seasons. Starting a new
-- season soft-resets every rating toward the baseline.

ALTER TABLE public."Ratings"
    ADD COLUMN IF NOT EXISTS "LastDecayAt" timestamp without time zone;

CREATE TABLE IF NOT EXISTS public."Seasons"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "StartedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Seasons" PRIMARY KEY ("Id")
);
