-- Clubs v2 and teams (N7): competition between groups, not just membership lists.
--
-- Clubs shipped as open-membership lists with a shareable join code. Three
-- things were recorded as follow-ups and are added here:
--
--   * JoinPolicy - a club that represents a real local scene often wants to
--     approve who joins. 'open' keeps the existing behaviour exactly, so no
--     existing club changes shape.
--   * ClubMembers.Status - pending members are rows in the same table rather
--     than a separate request table, because a pending member becomes an
--     active one by changing one value, and everything that lists members
--     already joins this table. Defaulting to 'active' leaves every existing
--     membership untouched.
--   * Ownership transfer needs no schema: it is an update to Clubs.OwnerId
--     plus the two ClubMembers rows, done in one transaction.
--
-- Teams are deliberately NOT clubs. A club is a place (a store, a city, a
-- Discord); a team is a roster that enters events as a unit, and the two have
-- different lifetimes - people stay in their local club for years and form
-- teams per season. A team may optionally belong to a club, which is how a
-- store fields several teams from its own membership.
--
-- TeamRatings mirrors Ratings: same pools, same shape, separate ladder. A team
-- rating is not the average of its members - a roster that wins together is
-- worth more than the sum of the individuals, and averaging would let a team
-- inherit a rating it never earned as a unit.

ALTER TABLE public."Clubs"
    ADD COLUMN IF NOT EXISTS "JoinPolicy" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'open';

ALTER TABLE public."ClubMembers"
    ADD COLUMN IF NOT EXISTS "Status" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'active';

-- Pending members are a small slice of a club and are read on their own
-- (the owner's approval queue), so the index only covers them.
CREATE INDEX IF NOT EXISTS "IX_ClubMembers_Pending"
    ON public."ClubMembers" USING btree
    ("ClubId" ASC NULLS LAST)
    TABLESPACE pg_default
    WHERE "Status" = 'pending';

CREATE TABLE IF NOT EXISTS public."Teams"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "CaptainId" integer NOT NULL,
    "ClubId" integer,
    "JoinCode" text COLLATE pg_catalog."default",
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Teams" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_Teams_Name" UNIQUE ("Name"),
    CONSTRAINT "FK_Teams_Users_CaptainId" FOREIGN KEY ("CaptainId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    -- A team outlives the club it was fielded from: disbanding the club
    -- orphans the team rather than deleting a roster and its event history.
    CONSTRAINT "FK_Teams_Clubs_ClubId" FOREIGN KEY ("ClubId")
        REFERENCES public."Clubs" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_Teams_JoinCode"
    ON public."Teams" ("JoinCode")
    WHERE "JoinCode" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_Teams_ClubId"
    ON public."Teams" USING btree
    ("ClubId" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."TeamMembers"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TeamId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Role" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'member',
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TeamMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_TeamMembers_Team_User" UNIQUE ("TeamId", "UserId"),
    CONSTRAINT "FK_TeamMembers_Teams" FOREIGN KEY ("TeamId")
        REFERENCES public."Teams" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TeamMembers_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_TeamMembers_UserId"
    ON public."TeamMembers" USING btree
    ("UserId" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."TeamRatings"
(
    "TeamId" integer NOT NULL,
    "Pool" text COLLATE pg_catalog."default" NOT NULL,
    "Rating" integer NOT NULL,
    "EventsPlayed" integer NOT NULL DEFAULT 0,
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TeamRatings" PRIMARY KEY ("TeamId", "Pool"),
    CONSTRAINT "FK_TeamRatings_Teams" FOREIGN KEY ("TeamId")
        REFERENCES public."Teams" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_TeamRatings_Pool_Rating"
    ON public."TeamRatings" USING btree
    ("Pool" ASC NULLS LAST, "Rating" DESC NULLS LAST)
    TABLESPACE pg_default;

-- One row per team per event, written when the event finishes. Keeping the
-- before/after on the row makes a team's rating history readable without
-- replaying events, and is what the team page shows.
CREATE TABLE IF NOT EXISTS public."TeamEventResults"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TournamentId" integer NOT NULL,
    "TeamId" integer NOT NULL,
    "Pool" text COLLATE pg_catalog."default" NOT NULL,
    "Rank" integer,
    "MatchWins" integer NOT NULL DEFAULT 0,
    "MatchLosses" integer NOT NULL DEFAULT 0,
    "RatingBefore" integer NOT NULL,
    "RatingAfter" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TeamEventResults" PRIMARY KEY ("Id"),
    -- Finishing an event twice must not rate a team twice.
    CONSTRAINT "UQ_TeamEventResults_Tournament_Team" UNIQUE ("TournamentId", "TeamId"),
    CONSTRAINT "FK_TeamEventResults_Tournaments" FOREIGN KEY ("TournamentId")
        REFERENCES public."Tournaments" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TeamEventResults_Teams" FOREIGN KEY ("TeamId")
        REFERENCES public."Teams" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_TeamEventResults_TeamId"
    ON public."TeamEventResults" USING btree
    ("TeamId" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;

-- Team events: a tournament whose entrants are teams. TeamSize is the roster
-- size each team fields; players still register and play individually, and
-- their results roll up to the team they registered under.
ALTER TABLE public."Tournaments"
    ADD COLUMN IF NOT EXISTS "TeamEvent" boolean NOT NULL DEFAULT false;

ALTER TABLE public."Tournaments"
    ADD COLUMN IF NOT EXISTS "TeamSize" integer;

ALTER TABLE public."TournamentPlayers"
    ADD COLUMN IF NOT EXISTS "TeamId" integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_TournamentPlayers_Teams'
    ) THEN
        ALTER TABLE public."TournamentPlayers"
            ADD CONSTRAINT "FK_TournamentPlayers_Teams" FOREIGN KEY ("TeamId")
            REFERENCES public."Teams" ("Id") MATCH SIMPLE
            ON UPDATE NO ACTION
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_TournamentPlayers_TeamId"
    ON public."TournamentPlayers" USING btree
    ("TeamId" ASC NULLS LAST)
    WHERE "TeamId" IS NOT NULL;
