-- Matchmaking metrics (N8): queue depth and how long people actually wait.
--
-- Everything else the operations dashboard needs is already recorded somewhere
-- - registrations in Users, games in Games, events in Tournaments - and is
-- better derived than duplicated, so this migration adds exactly one table.
--
-- The matchmaking queue is the one exception: it lives entirely in memory in
-- MatchmakingService, so a queue that was ten deep at 8pm leaves no trace by
-- 9pm. "Is the queue healthy" cannot be answered retroactively without
-- writing something down as it happens.
--
-- Two kinds of row share the table because they answer one question together:
--   * a depth sample (WaitSeconds NULL) - the queue was N deep at this moment
--   * a match record (WaitSeconds set)  - someone waited this long and got a game
-- Splitting them would mean two queries and a join to chart "depth against
-- wait", which is the only chart either is interesting on.

CREATE TABLE IF NOT EXISTS public."MatchmakingMetrics"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 CACHE 1 ),
    "RecordedAt" timestamp without time zone NOT NULL,
    "Format" text COLLATE pg_catalog."default",
    "QueueDepth" integer NOT NULL DEFAULT 0,
    "WaitSeconds" integer,
    CONSTRAINT "PK_MatchmakingMetrics" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

-- Every dashboard read is "the last N days", so time leads the index.
CREATE INDEX IF NOT EXISTS "IX_MatchmakingMetrics_RecordedAt"
    ON public."MatchmakingMetrics" USING btree
    ("RecordedAt" DESC NULLS LAST)
    TABLESPACE pg_default;
