-- Collection import as a resumable job: one row per "import everything I own",
-- worked a few decks at a time by the lobby sweep.
--
-- Importing a whole Decks of KeyForge collection used to happen entirely in the
-- browser. The server listed the collection and handed back uuids; the client
-- looped POST /api/decks over them. Master Vault meters hard enough that a
-- 257-deck collection takes minutes, so closing the modal or navigating away
-- part-way through was the ordinary outcome rather than the exceptional one,
-- and the import died wherever it had got to - with no record of which decks
-- had landed, so the retry started again from the top.
--
-- Moving that loop server-side only fixes it if the progress outlives the
-- process running it. Hence a table rather than an in-memory queue: the lobby
-- is restarted for every deploy, and a restart mid-import has to resume, not
-- start over and not silently drop the job.
--
-- WHY THERE IS NO DOK API KEY COLUMN HERE
--
-- Listing a player's collection needs their Decks of KeyForge API key.
-- Importing the decks does not - each deck is fetched from Master Vault, which
-- has no notion of a DoK key at all. So the key is used synchronously, while
-- the job is being created, purely to turn "this player's collection" into a
-- list of uuids, and is then discarded. The job holds uuids and nothing else,
-- which is the whole reason the work can be deferred at all.
--
-- That absence is load-bearing rather than tidiness. A worker that needed the
-- key would have to store it, and a stored third-party credential is one that
-- leaks - into backups, into a support query, into whatever a later admin
-- screen renders. DoK issues one key per account and generating a new one
-- voids the old instantly, so a leak here costs the player their key
-- everywhere else they use it. There is no column to populate, so no later
-- change can start populating one by accident.
--
-- WHY "Username" IS DENORMALISED ONTO THE JOB
--
-- DeckService.create builds the deck's identity from a username, not a user
-- id. The worker calls it once per deck, hundreds of times per job, and
-- without this column every one of those calls would first join "Users" to
-- answer a question whose answer was already known when the job was created.
-- Copying the name onto the job trades one text column for that entire join.
--
-- WHY "Uuids" IS ONE BLOB, WRITTEN ONCE
--
-- The uuid list is written at creation and never rewritten. Progress moves
-- "Cursor" and the counters, which are small fixed-width updates to the same
-- row. The alternatives both cost hundreds of writes per import for data that
-- never changes: a row per deck means a row per deck to insert and re-read,
-- and rewriting the JSON blob after each deck means rewriting the entire
-- collection to record that one deck of it is done.
--
-- The price is that a job is capped by what fits comfortably in a text column.
-- That is not a real limit here: the service refuses an import larger than
-- dok.maxImportDecks (default 500) long before this matters, and 500 uuids of
-- JSON is roughly twenty kilobytes.

CREATE TABLE IF NOT EXISTS public."DeckImportJobs"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    -- Denormalised from "Users" so the worker does not join per deck - see above.
    "Username" text COLLATE pg_catalog."default" NOT NULL,
    -- 'pending' | 'running' | 'done' | 'cancelled'. The last two are terminal,
    -- and are what release the one-live-job-per-user index at the bottom of
    -- this file: cancelling is how a player who wants to start over is allowed
    -- to start over.
    "Status" text COLLATE pg_catalog."default" NOT NULL,
    -- JSON array of Master Vault deck ids. Written once at creation - see above.
    "Uuids" text COLLATE pg_catalog."default" NOT NULL,
    -- Index into "Uuids" of the next deck to attempt. A deck that cannot be
    -- imported still advances the cursor and lands in "Failed"/"Reasons",
    -- because one bad deck must not wedge the rest of the collection behind
    -- it. Rate limiting is the exception: that deck has not been dealt with,
    -- so the job pauses on it rather than moving past it.
    "Cursor" integer NOT NULL DEFAULT 0,
    "Imported" integer NOT NULL DEFAULT 0,
    "AlreadyOwned" integer NOT NULL DEFAULT 0,
    "Failed" integer NOT NULL DEFAULT 0,
    -- JSON object of failure reason -> count. Aggregated rather than one row
    -- per failure because the only consumer is a summary the player reads once
    -- ("12 decks are from an unsupported expansion"), and counts keep the
    -- whole job in a single row that a status poll can fetch with one select.
    "Reasons" text COLLATE pg_catalog."default",
    "LastError" text COLLATE pg_catalog."default",
    -- Circuit breaker, the same shape as "DeckCatalogState": when Master Vault
    -- starts returning 429s the polite response is to stop asking for a while,
    -- and the pause has to be in the database because the sweep that observes
    -- the rate limit may not be the process that runs the job next.
    "PausedUntil" timestamp without time zone,
    "ConsecutiveFailures" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_DeckImportJobs" PRIMARY KEY ("Id"),
    -- CASCADE: a job is a piece of work being done on behalf of an account and
    -- means nothing without it. Nobody audits a deleted player's import.
    CONSTRAINT "FK_DeckImportJobs_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

-- ONE LIVE JOB PER USER, ENFORCED BY THE DATABASE
--
-- Two live jobs for the same player would work the same collection twice: they
-- race on the same decks, both count the same import as their own progress, and
-- between them double the load this puts on Master Vault - which is the one
-- upstream whose patience the whole design is spending carefully.
--
-- The constraint lives here rather than in the service because the service
-- cannot enforce it. "Does this user already have a job" followed by "then
-- insert one" is two statements, and the lobby is a process that can be run
-- more than once; a check in application code is a check that two processes
-- pass simultaneously. Partial, so finished and cancelled jobs accumulate as
-- history without ever blocking the next import.
CREATE UNIQUE INDEX IF NOT EXISTS "IX_DeckImportJobs_ActivePerUser"
    ON public."DeckImportJobs" ("UserId")
    WHERE "Status" IN ('pending', 'running');

-- The sweep's claim query: oldest live job first, so a queue of imports is
-- served in the order players asked rather than by whichever row the planner
-- happened to reach.
CREATE INDEX IF NOT EXISTS "IX_DeckImportJobs_Status_CreatedAt"
    ON public."DeckImportJobs" USING btree
    ("Status" ASC NULLS LAST, "CreatedAt" ASC NULLS LAST)
    TABLESPACE pg_default;
