-- ARCHON (N21): the learning bot - policies, its training diary, and the
-- Champion's Challenge upgrades that ride with it.
--
-- "BotPolicies" holds every brain the sparring partner has ever had: the
-- model itself as one JSON document (weights plus per-card weights - small
-- enough that a row IS the deployment), its lineage, and its arena record.
-- Exactly one row is 'champion' at a time; a 'candidate' earns its place by
-- beating the champion over enough games that the Wilson bound clears 50%,
-- and a beaten candidate retires with its record kept. Promotion is a
-- status flip, rollback is the same flip backwards - no redeploy touches a
-- model.
--
-- "BotTrainingGames" is the diary: one row per logged sparring game, the
-- decisions it contained (features, by side) and who won, which is all
-- supervised learning needs. It is a working set, not an archive - the
-- sweep prunes it to a configured depth, newest kept.
--
-- The ALTERs: showcase games record the deep planner's annotations on the
-- game row itself ("Deep"/"Annotations"), and roster slots gain the
-- randomizer's bookkeeping ("Random"/"RandomGamesTarget" - swap this deck
-- for a fresh random one once it has played its target).

CREATE TABLE IF NOT EXISTS public."BotPolicies"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Version" integer NOT NULL,
    -- 'candidate' | 'champion' | 'retired'
    "Status" text COLLATE pg_catalog."default" NOT NULL,
    "Model" jsonb NOT NULL,
    "TrainedGames" integer NOT NULL DEFAULT 0,
    "ArenaWins" integer NOT NULL DEFAULT 0,
    "ArenaLosses" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp without time zone NOT NULL,
    "PromotedAt" timestamp without time zone,
    CONSTRAINT "PK_BotPolicies" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_BotPolicies_Version" UNIQUE ("Version")
)

TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."BotTrainingGames"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    -- The champion whose play produced this game, for lineage. NULL for the
    -- heuristic bot's games - version zero of the species.
    "PolicyVersion" integer,
    -- 'challenger-alpha' | 'challenger-omega'
    "WinnerSide" text COLLATE pg_catalog."default" NOT NULL,
    "Decisions" jsonb NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_BotTrainingGames" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

-- The trainer fetches newest-first and the pruner deletes oldest-first;
-- both are this index.
CREATE INDEX IF NOT EXISTS "IX_BotTrainingGames_Id"
    ON public."BotTrainingGames" USING btree
    ("Id" DESC NULLS LAST)
    TABLESPACE pg_default;

-- Showcase games: played by the deep planner, carrying its annotations.
ALTER TABLE public."ProvingGroundsGames"
    ADD COLUMN IF NOT EXISTS "Deep" boolean NOT NULL DEFAULT false;

ALTER TABLE public."ProvingGroundsGames"
    ADD COLUMN IF NOT EXISTS "Annotations" jsonb;

-- Randomizer slots: this enrollment was chosen by the randomizer, and swaps
-- for a fresh random deck once it has played its target.
ALTER TABLE public."ProvingGroundsDecks"
    ADD COLUMN IF NOT EXISTS "Random" boolean NOT NULL DEFAULT false;

ALTER TABLE public."ProvingGroundsDecks"
    ADD COLUMN IF NOT EXISTS "RandomGamesTarget" integer;
