-- ARCHON (F9): the practice bots - one per house, each an ordinary account.
--
-- The lobby keeps an open table hosted by one of these, and a bot only ever
-- plays decks containing its own house. This table is the binding between a
-- house and the account that plays it.
--
-- WHY THE ACCOUNT IS A REAL "Users" ROW
--
-- Every path a player takes - the pending game, deck selection, the game
-- node's player construction, the lobby seat with its avatar - already works
-- for a user and nothing else. Giving a bot a real row means none of that
-- needed a second kind of player, and it is also what lets an admin edit a
-- bot's name, picture and profile with the machinery that already edits a
-- person's. The account is unenterable: its stored password is a sentinel
-- that is not a bcrypt hash, so every login comparison fails.
--
-- WHY THE BINDING IS A TABLE RATHER THAN THE NAME
--
-- The house decides which decks the bot may play, so it is the bot's
-- identity - and the name is not, because an admin may change it. Keying on
-- the name would mean a rename silently rebinds the character to a different
-- set of decks, or orphans it. "House" is unique for the same reason: a
-- house has exactly one bot, and two accounts claiming Logos would make
-- "which deck may this bot play" ambiguous.

CREATE TABLE IF NOT EXISTS public."Bots"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "House" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "UserId" integer NOT NULL,
    -- Per-bot off switch, so an admin can retire one character without
    -- turning the whole practice table off.
    "Enabled" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_Bots" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_Bots_House" UNIQUE ("House"),
    -- One account plays one house: the account IS the character.
    CONSTRAINT "UQ_Bots_UserId" UNIQUE ("UserId"),
    -- CASCADE: a bot without its account is not a bot. Deleting the account
    -- (an admin cleaning up) retires the character, and the next sweep
    -- recreates it from the roster defaults.
    CONSTRAINT "FK_Bots_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

-- ARCHON (F9): adopt the account from the single-bot version.
--
-- The first cut of this feature ran one bot, keyed by an email built from its
-- NAME. The roster keys on the house instead, so without this the Logos bot
-- would find its default name ('HelperBot') already taken by that account,
-- refuse to seat a bot in what it cannot prove is its own, and never play.
-- Re-keying the existing account keeps its games, picture and profile.
--
-- Both statements match nothing on a fresh database, which is why this file
-- and its schema twin stay identical.
UPDATE public."Users"
SET "Email" = 'bot+logos@archon-bots.invalid'
WHERE "Email" = 'bot+helperbot@helper-bot.invalid';

INSERT INTO public."Bots" ("House", "UserId")
SELECT 'logos', u."Id"
FROM public."Users" u
WHERE u."Email" = 'bot+logos@archon-bots.invalid'
ON CONFLICT ("House") DO NOTHING;
