-- ARCHON (N32): the Vault Tour - a slate of decks against a field somebody won
-- a tournament with.
--
-- The mirror lab measures a deck against the company it keeps; the Gauntlet
-- measures it against a random sample of everything that exists. Neither answers
-- the question a competitive player actually asks, which is "how does this hold
-- up against what wins events". That field is not a sample, it is a CURATED
-- list: the decks that took first and second at real tournaments, entered by an
-- operator who knows which those were.
--
-- Three tables, and the separations between them are the point:
--
--  * The field is site-wide and admin-owned. One deck, one row, hydrated once.
--  * A member's slate is THREE decks and is not the eight-deck roster. Different
--    question, different sample, different budget - a deck may sit in both.
--  * The results live in their own table and NEVER move ARI. ARI is a rating on
--    the SAS scale fed by games against representative opposition; feeding it
--    games against a hand-picked field of tournament winners would import the
--    operator's choice of opponents straight into the platform's deck rating,
--    where nobody could see it. The matrix is the deliverable here, not a number
--    that leaks into everything else.

-- The field: tournament decks, hydrated the same way Gauntlet pool decks are.
CREATE TABLE IF NOT EXISTS public."VaultTourDecks"
(
    "Uuid" text COLLATE pg_catalog."default" NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Expansion" integer NOT NULL,
    -- Comma-separated house codes, as the catalog stores them.
    "Houses" text COLLATE pg_catalog."default",
    -- The parsed card list, exactly the shape the engine's selectDeck wants.
    "Cards" jsonb,
    -- false when this server cannot simulate the deck: a card it has no data
    -- for, or a house count the engine will not accept. Kept as a row rather
    -- than refused outright so the operator can see WHY their entry is not
    -- playing, instead of watching it silently never appear.
    "Playable" boolean NOT NULL DEFAULT false,
    "MissingCards" text COLLATE pg_catalog."default",
    -- What makes this deck worth playing against, and the whole reason the field
    -- is curated rather than crawled.
    "Event" text COLLATE pg_catalog."default" NOT NULL,
    -- 'winner' | 'runner-up' | 'finalist' | 'other' - free enough for a format
    -- this project does not control, checked in the service.
    "Placing" text COLLATE pg_catalog."default" NOT NULL,
    "EventDate" date,
    "AddedByUserId" integer,
    "FetchedAt" timestamp without time zone NOT NULL,
    -- Spreads the draw across the field rather than favouring whatever postgres
    -- hands back first.
    "LastPlayedAt" timestamp without time zone,
    "GamesPlayed" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_VaultTourDecks" PRIMARY KEY ("Uuid"),
    -- The operator who added it, kept for provenance. SET NULL rather than
    -- CASCADE: a field entry outlives the admin account that typed it in.
    CONSTRAINT "FK_VaultTourDecks_Users" FOREIGN KEY ("AddedByUserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

-- The draw: playable decks, least recently played first.
CREATE INDEX IF NOT EXISTS "IX_VaultTourDecks_Playable"
    ON public."VaultTourDecks" USING btree
    ("Playable" ASC NULLS LAST, "LastPlayedAt" ASC NULLS FIRST)
    TABLESPACE pg_default;

-- A member's slate: at most three decks, separate from the eight-deck roster.
CREATE TABLE IF NOT EXISTS public."VaultTourEntries"
(
    "UserId" integer NOT NULL,
    "DeckId" integer NOT NULL,
    "EnrolledAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_VaultTourEntries" PRIMARY KEY ("UserId", "DeckId"),
    CONSTRAINT "FK_VaultTourEntries_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_VaultTourEntries_Decks" FOREIGN KEY ("DeckId")
        REFERENCES public."Decks" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

-- The results, from the member's deck's point of view - one row per game, so
-- "Won" is unambiguous and every cell of the matrix is a single-column filter.
CREATE TABLE IF NOT EXISTS public."VaultTourGames"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "DeckId" integer NOT NULL,
    "OpponentUuid" text COLLATE pg_catalog."default" NOT NULL,
    -- Denormalised so a result stays readable if a field entry is ever removed,
    -- and so the matrix does not join for its labels.
    "OpponentName" text COLLATE pg_catalog."default",
    "OpponentEvent" text COLLATE pg_catalog."default",
    "OpponentPlacing" text COLLATE pg_catalog."default",
    "Won" boolean NOT NULL,
    "MyKeys" smallint NOT NULL,
    "OpponentKeys" smallint NOT NULL,
    "Turns" smallint NOT NULL,
    "WentFirst" boolean NOT NULL,
    -- Which of the three sparring styles flew it, both seats (see labPersonas).
    "Persona" text COLLATE pg_catalog."default",
    "DurationMs" integer,
    "FinishedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_VaultTourGames" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VaultTourGames_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_VaultTourGames_Decks" FOREIGN KEY ("DeckId")
        REFERENCES public."Decks" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

-- The matrix reads one member's games per deck; the sweep counts one deck's
-- games since UTC midnight. Both are this index.
CREATE INDEX IF NOT EXISTS "IX_VaultTourGames_Deck"
    ON public."VaultTourGames" USING btree
    ("DeckId" ASC NULLS LAST, "FinishedAt" DESC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_VaultTourGames_User_FinishedAt"
    ON public."VaultTourGames" USING btree
    ("UserId" ASC NULLS LAST, "FinishedAt" DESC NULLS LAST)
    TABLESPACE pg_default;
