-- ARCHON (N38): the LLM teacher's workbench.
--
-- The learning loop has two teachers: outcomes (plentiful, noisy) and the
-- deep bot's search (measured, expensive CPU). This adds a third - a language
-- model that can actually read the cards - under the same discipline the
-- other two live by: budgets, calibration, and no way to quietly make the
-- bot worse.
--
-- One table. Sparring and deep games CAPTURE positions here (a readable
-- board summary, the candidate moves as decision records, and - when the
-- position came from a deep game's analyzed decision - the win probability
-- the rollouts measured for each candidate). A scheduled review then spends
-- a small weekly token budget asking the LLM to score the candidates:
--
--  * Positions WITH deep targets are calibration: the LLM's picks are
--    compared against what the search measured, and the running agreement
--    is the teacher's licence to teach.
--  * Positions WITHOUT them become training lessons - but only while the
--    licence holds. An unvalidated (or drifting) teacher reviews nothing but
--    calibration positions until it earns the diary back.
--
-- Lessons that do get written go through the ordinary diary
-- ("BotTrainingGames") as target-carrying rows with their own gradient
-- weight, so everything downstream - training, the candidate arena, the
-- SPRT title fight - already applies. A bad teacher's worst case is a
-- retired candidate.
--
-- The table is a working set like the diary, pruned to a few hundred rows;
-- the model is the memory.
CREATE TABLE IF NOT EXISTS public."ChallengeLlmPositions"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    -- The champion whose play produced the game. NULL for the heuristics.
    "PolicyVersion" integer,
    -- Who won the game the position came from - kept because a lesson row is
    -- still a record of a real game, though targets are what train.
    "WinnerSide" text COLLATE pg_catalog."default" NOT NULL,
    -- The board as the deciding seat saw it, in plain terms (names, amber,
    -- keys) - what the reviewer's prompt is rendered from.
    "Summary" jsonb NOT NULL,
    -- One entry per candidate move: its decision record
    -- (labFeatures.decisionRecord) plus a readable label.
    "Candidates" jsonb NOT NULL,
    -- Deep-game positions only: the win probability the search measured per
    -- candidate, index-aligned with "Candidates". The calibration standard.
    "DeepTargets" jsonb,
    -- 'pending' | 'reviewed' | 'failed'
    "Status" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending',
    -- The review: the LLM's scores, agreement with the deep bot where
    -- measurable, and whether lessons were written.
    "Review" jsonb,
    "CreatedAt" timestamp without time zone NOT NULL,
    "ReviewedAt" timestamp without time zone,
    CONSTRAINT "PK_ChallengeLlmPositions" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

-- The review takes pending rows oldest-first; the pruner deletes oldest.
CREATE INDEX IF NOT EXISTS "IX_ChallengeLlmPositions_Status"
    ON public."ChallengeLlmPositions" USING btree
    ("Status", "Id")
    TABLESPACE pg_default;

-- The weekly token budget and the daily capture budget both count by time.
CREATE INDEX IF NOT EXISTS "IX_ChallengeLlmPositions_CreatedAt"
    ON public."ChallengeLlmPositions" USING btree
    ("CreatedAt")
    TABLESPACE pg_default;
