-- ARCHON (N44): the assay - card knowledge from measurement, not estimation.
--
-- Decks of KeyForge's numbers come from years of expert curation because no
-- human can play enough games to MEASURE a card. This platform can. Three
-- tables and a cursor turn the simulator into the instrument:
--
--  * "ChallengeCardObserved" / "ChallengeCardPairObserved" are the FREE
--    phase: an incremental miner walks the training diary and aggregates,
--    per card actually played, games and wins - and the same for pairs the
--    synergy tags hypothesize about, when both halves saw play on the same
--    side. Observational, confounded by deck quality, and therefore
--    prior-grade evidence: it audits the tags (a claimed combo whose
--    measured lift is negative gets flagged for the advisor), it does not
--    convict.
--
--  * "ChallengeCardExperiments" is the CONTROLLED phase: two synthetic
--    decks identical except for one card (the target versus a duplicate of
--    a filler - KeyForge allows duplicates), played head to head on paired
--    seeds by the same pilot on both sides, for a fixed budget of games.
--    The win rate of the target's arm IS the card's marginal value,
--    measured causally. With "PartnerCardId" set, the host decks both carry
--    the hypothesized partner, so the same instrument measures the card's
--    value WITH its combo available - and the difference against its
--    neutral experiment is the synergy, in win percentage.
--
-- Assay games exist only as counters here: they never touch
-- ProvingGroundsGames, ARI, the diary, or any statistic a member sees.
-- Fidelity is capped by the champion's play quality, which is why rows
-- carry timestamps: re-measuring under a stronger champion is expected,
-- not an anomaly.

CREATE TABLE IF NOT EXISTS public."ChallengeCardObserved"
(
    "CardId" text COLLATE pg_catalog."default" NOT NULL,
    "Games" integer NOT NULL DEFAULT 0,
    "Wins" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_ChallengeCardObserved" PRIMARY KEY ("CardId")
)

TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."ChallengeCardPairObserved"
(
    -- Sorted, so a pair is one row - the persona duels' convention.
    "CardA" text COLLATE pg_catalog."default" NOT NULL,
    "CardB" text COLLATE pg_catalog."default" NOT NULL,
    "Games" integer NOT NULL DEFAULT 0,
    "Wins" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_ChallengeCardPairObserved" PRIMARY KEY ("CardA", "CardB")
)

TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."ChallengeCardExperiments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CardId" text COLLATE pg_catalog."default" NOT NULL,
    -- NULL: the card measured on neutral ground. Set: both arms' hosts
    -- carry this partner, so the measurement is "with the combo available".
    "PartnerCardId" text COLLATE pg_catalog."default",
    -- The duplicate filler standing where the target stands in the other
    -- arm - recorded because the measurement is only meaningful relative
    -- to what replaced the card.
    "ReplacementCardId" text COLLATE pg_catalog."default" NOT NULL,
    "Games" integer NOT NULL DEFAULT 0,
    "Wins" integer NOT NULL DEFAULT 0,
    -- 'running' | 'measured' | 'abandoned'
    "Status" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'running',
    "CreatedAt" timestamp without time zone NOT NULL,
    "MeasuredAt" timestamp without time zone,
    CONSTRAINT "PK_ChallengeCardExperiments" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

-- One experiment runs at a time; history reads newest-first.
CREATE INDEX IF NOT EXISTS "IX_ChallengeCardExperiments_Status"
    ON public."ChallengeCardExperiments" USING btree
    ("Status", "Id" DESC)
    TABLESPACE pg_default;

-- The miner's cursor: the diary prunes itself, so progress is tracked by
-- the last diary row already folded into the aggregates.
CREATE TABLE IF NOT EXISTS public."ChallengeAssayState"
(
    "Id" integer NOT NULL DEFAULT 1,
    "MinedThroughDiaryId" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_ChallengeAssayState" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;
