-- ARCHON (N14): self-serve TestFlight requests.
--
-- Apple caps external TestFlight testers, so `/mobile/ios` cannot just link
-- to the beta the way `/mobile/android` will - someone has to work through
-- requests in order. This table is that queue: a signed-in player asks once,
-- the request sits here until an admin clears it (adds them in App Store
-- Connect and marks it done), and a repeat visit to the page shows the
-- pending state instead of the form again.
--
-- SET NULL on both user references, matching "BugReports": the queue is a
-- record of who asked and it should survive account deletion rather than
-- silently losing rows, the same reasoning that table already settled.

CREATE TABLE IF NOT EXISTS public."IosBetaRequests"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer,
    "AppleId" text COLLATE pg_catalog."default" NOT NULL,
    "Status" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending',
    "ClearedBy" integer,
    "ClearedAt" timestamp without time zone,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_IosBetaRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IosBetaRequests_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT "FK_IosBetaRequests_ClearedBy" FOREIGN KEY ("ClearedBy")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_IosBetaRequests_Status"
    ON public."IosBetaRequests" USING btree
    ("Status" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;

-- One pending request per player at a time - asking twice should not build
-- two rows for an admin to work through.
CREATE UNIQUE INDEX IF NOT EXISTS "UX_IosBetaRequests_UserId_Pending"
    ON public."IosBetaRequests" USING btree ("UserId")
    TABLESPACE pg_default
    WHERE "Status" = 'pending' AND "UserId" IS NOT NULL;
