export const TAG_TYPES = {
    NEWS: 'News',
    CARDS: 'Cards',
    FACTIONS: 'Factions',
    DECKS: 'Decks',
    USER: 'User',
    SESSIONS: 'Sessions',
    BLOCKLIST: 'Blocklist',
    ADMIN: 'Admin',
    BANLIST: 'Banlist',
    GAMES: 'Games',
    LOBBY: 'Lobby',
    OIDC: 'Oidc',
    LOCATION: 'Location',
    TOURNAMENTS: 'Tournaments',
    FRIENDS: 'Friends',
    CLUBS: 'Clubs',
    STORES: 'Stores',
    RATINGS: 'Ratings',
    BUG_REPORTS: 'BugReports'
};
