-- Table: public."GamePlayers"

-- DROP TABLE public."GamePlayers";

CREATE TABLE public."GamePlayers"
(
    "GameId" integer NOT NULL,
    "PlayerId" integer NOT NULL,
    "DeckId" integer,
    -- ARCHON: the deck's Master Vault uuid, recorded at game time. "DeckId" is
    -- ON DELETE SET NULL, so deleting a deck used to erase its game record
    -- rather than archive it; this outlives the row and is what re-links the
    -- games when the deck is imported again. See migration 71.
    "DeckUuid" text,
    "Keys" integer,
    "Turn" integer,
    "Wins" integer,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT "PK_GamePlayers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GamePlayers_Decks_DeckId" FOREIGN KEY ("DeckId")
        REFERENCES public."Decks" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT "FK_GamePlayers_Games_GameId" FOREIGN KEY ("GameId")
        REFERENCES public."Games" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_GamePlayers_Users_PlayerId" FOREIGN KEY ("PlayerId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."GamePlayers"
    OWNER to keyteki;
-- Index: IX_GamePlayers_DeckId

-- DROP INDEX public."IX_GamePlayers_DeckId";

CREATE INDEX "IX_GamePlayers_DeckId"
    ON public."GamePlayers" USING btree
    ("DeckId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_GamePlayers_GameId_PlayerId

-- DROP INDEX public."IX_GamePlayers_GameId_PlayerId";

CREATE UNIQUE INDEX "IX_GamePlayers_GameId_PlayerId"
    ON public."GamePlayers" USING btree
    ("GameId" ASC NULLS LAST, "PlayerId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_GamePlayers_PlayerId

-- DROP INDEX public."IX_GamePlayers_PlayerId";

CREATE INDEX "IX_GamePlayers_PlayerId"
    ON public."GamePlayers" USING btree
    ("PlayerId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_GamePlayers_DeckUuid

-- DROP INDEX public."IX_GamePlayers_DeckUuid";

-- Partial: null for alliance and standalone decks, which have no Master Vault
-- uuid, and nothing looks a null one up.
CREATE INDEX "IX_GamePlayers_DeckUuid"
    ON public."GamePlayers" USING btree
    ("DeckUuid" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default
    WHERE "DeckUuid" IS NOT NULL;