-- Table: public."UserOidcIdentities"
-- Links external OpenID Connect identities (e.g. Keybringer/Keycloak
-- subjects) to local user accounts. A user may have identities from
-- several providers; each provider subject maps to exactly one user.

CREATE TABLE IF NOT EXISTS public."UserOidcIdentities"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "Provider" text COLLATE pg_catalog."default" NOT NULL,
    "Subject" text COLLATE pg_catalog."default" NOT NULL,
    "Email" text COLLATE pg_catalog."default",
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_UserOidcIdentities" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_UserOidcIdentities_Provider_Subject" UNIQUE ("Provider", "Subject"),
    CONSTRAINT "FK_UserOidcIdentities_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_UserOidcIdentities_UserId"
    ON public."UserOidcIdentities" USING btree
    ("UserId" ASC NULLS LAST)
    TABLESPACE pg_default;
