-- Table: public."RatingHistory"
-- One row per player per rated game: the full inputs and outputs of the
-- rating calculation, including a snapshot of the Elo config used, so
-- ratings are auditable and recalculable after config changes.

CREATE TABLE IF NOT EXISTS public."RatingHistory"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "GameId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "OpponentId" integer NOT NULL,
    "Pool" text COLLATE pg_catalog."default" NOT NULL,
    "Won" boolean NOT NULL,
    "RatingBefore" integer NOT NULL,
    "RatingAfter" integer NOT NULL,
    "Expected" real,
    "OwnSas" integer,
    "OpponentSas" integer,
    "KeyDiff" integer,
    "ResultType" text COLLATE pg_catalog."default",
    "ConfigSnapshot" jsonb,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_RatingHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_RatingHistory_Game_User" UNIQUE ("GameId", "UserId"),
    CONSTRAINT "FK_RatingHistory_Games_GameId" FOREIGN KEY ("GameId")
        REFERENCES public."Games" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_RatingHistory_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_RatingHistory_UserId_Pool"
    ON public."RatingHistory" USING btree
    ("UserId" ASC NULLS LAST, "Pool" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;
