-- Table: public."Tournaments"
-- Archon Arena tournament engine (Phase 7): the native, in-platform event
-- system. All tournaments run on the platform itself.

CREATE TABLE IF NOT EXISTS public."Tournaments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "OrganizerId" integer NOT NULL,
    "Format" text COLLATE pg_catalog."default" NOT NULL,
    "GameFormat" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'archon',
    "Mode" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'online',
    "Status" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'registration',
    "RoundCount" integer,
    "CurrentRound" integer NOT NULL DEFAULT 0,
    -- v2: scheduling, registration and format controls
    "StartTime" timestamp without time zone,
    "PlayerCap" integer,
    "BestOf" integer NOT NULL DEFAULT 1,
    "PlayoffBestOf" integer,
    "CutTo" integer,
    "Stage" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'main',
    "SeedMethod" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'registration',
    "Visibility" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'public',
    "JoinCode" text COLLATE pg_catalog."default",
    "RoundTimerMinutes" integer,
    "RoundStartedAt" timestamp without time zone,
    -- When the current round is due to end (migration 49). Stored rather
    -- than recomputed per client, so that extending a round is one edit
    -- everybody sees instead of a number each page works out for itself.
    "RoundEndsAt" timestamp without time zone,
    "CheckInOpenedAt" timestamp without time zone,
    "RatedGames" boolean NOT NULL DEFAULT false,
    "RequireDeckRegistration" boolean NOT NULL DEFAULT false,
    "SasMin" integer,
    "SasMax" integer,
    "HideDecklists" boolean NOT NULL DEFAULT false,
    "GameTimeLimit" integer,
    "Announcement" text COLLATE pg_catalog."default",
    -- KeyForge-specific conditions (migration 33)
    "DeckSwapPolicy" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'locked',
    "AllowedSets" jsonb,
    "RequiredHouses" jsonb,
    "BannedHouses" jsonb,
    "SasChainHandicap" boolean NOT NULL DEFAULT false,
    "ChainsPerMatchWin" integer NOT NULL DEFAULT 0,
    "Triad" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp without time zone NOT NULL,
    "StartedAt" timestamp without time zone,
    "FinishedAt" timestamp without time zone,
    CONSTRAINT "PK_Tournaments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tournaments_Users_OrganizerId" FOREIGN KEY ("OrganizerId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_Tournaments_Status"
    ON public."Tournaments" USING btree
    ("Status" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_Tournaments_Visibility"
    ON public."Tournaments" USING btree
    ("Visibility" ASC NULLS LAST, "Status" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;
