-- Table: public."Tournaments"
-- Archon Arena tournament engine (Phase 7). Distinct from the legacy
-- Challonge integration; this is the native event system.

CREATE TABLE IF NOT EXISTS public."Tournaments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "OrganizerId" integer NOT NULL,
    "Format" text COLLATE pg_catalog."default" NOT NULL,
    "GameFormat" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'archon',
    "Mode" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'online',
    "Status" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'registration',
    "RoundCount" integer,
    "CurrentRound" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp without time zone NOT NULL,
    "StartedAt" timestamp without time zone,
    "FinishedAt" timestamp without time zone,
    CONSTRAINT "PK_Tournaments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tournaments_Users_OrganizerId" FOREIGN KEY ("OrganizerId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_Tournaments_Status"
    ON public."Tournaments" USING btree
    ("Status" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;
