-- Table: public."TournamentPlayers"
-- Registrations for tournaments; Dropped players stay for history but
-- stop being paired.

CREATE TABLE IF NOT EXISTS public."TournamentPlayers"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TournamentId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Dropped" boolean NOT NULL DEFAULT false,
    "Seed" integer,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TournamentPlayers" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_TournamentPlayers_Tournament_User" UNIQUE ("TournamentId", "UserId"),
    CONSTRAINT "FK_TournamentPlayers_Tournaments" FOREIGN KEY ("TournamentId")
        REFERENCES public."Tournaments" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentPlayers_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;
