-- Table: public."TournamentMatches"
-- One row per pairing per round. Player2Id NULL means a bye (auto-win
-- for Player1). WinnerId NULL means unreported.

CREATE TABLE IF NOT EXISTS public."TournamentMatches"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TournamentId" integer NOT NULL,
    "Round" integer NOT NULL,
    "TableNumber" integer,
    "Player1Id" integer NOT NULL,
    "Player2Id" integer,
    "WinnerId" integer,
    "ReportedBy" integer,
    "ReportedAt" timestamp without time zone,
    CONSTRAINT "PK_TournamentMatches" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TournamentMatches_Tournaments" FOREIGN KEY ("TournamentId")
        REFERENCES public."Tournaments" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentMatches_Player1" FOREIGN KEY ("Player1Id")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentMatches_Player2" FOREIGN KEY ("Player2Id")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_TournamentMatches_Tournament_Round"
    ON public."TournamentMatches" USING btree
    ("TournamentId" ASC NULLS LAST, "Round" ASC NULLS LAST)
    TABLESPACE pg_default;
