-- Table: public."TournamentMatches"
-- One row per pairing per round. Player2Id NULL with a bye ResultType
-- means a bye (auto-win for Player1). WinnerId NULL with no ResultType
-- means unreported. Elimination brackets pre-create slots whose players
-- are unknown (both player columns NULL) and fill them from the source
-- match references as results come in. Round is the gating "wave"
-- number; Bracket/BracketRound/BracketPos position a match inside the
-- winners ('W') / losers ('L') / grand finals ('GF') structure.
-- Player1Wins/Player2Wins carry best-of series game scores.

CREATE TABLE IF NOT EXISTS public."TournamentMatches"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TournamentId" integer NOT NULL,
    "Round" integer NOT NULL,
    "TableNumber" integer,
    "Player1Id" integer,
    "Player2Id" integer,
    "WinnerId" integer,
    "ReportedBy" integer,
    "ReportedAt" timestamp without time zone,
    "Bracket" text COLLATE pg_catalog."default",
    "BracketRound" integer,
    "BracketPos" integer,
    "P1SourceMatchId" integer,
    "P1SourceIsLoser" boolean NOT NULL DEFAULT false,
    "P2SourceMatchId" integer,
    "P2SourceIsLoser" boolean NOT NULL DEFAULT false,
    "Player1Wins" integer NOT NULL DEFAULT 0,
    "Player2Wins" integer NOT NULL DEFAULT 0,
    "BestOf" integer NOT NULL DEFAULT 1,
    "ResultType" text COLLATE pg_catalog."default",
    -- Triad ban/pick state (migration 33): PxBannedDeckId is the deck
    -- of player X banned by their opponent; PxDeckId the chosen deck.
    "P1BannedDeckId" integer,
    "P2BannedDeckId" integer,
    "P1DeckId" integer,
    "P2DeckId" integer,
    -- Result integrity (migration 49). A decided match with ConfirmedBy
    -- NULL was reported by one player and not yet agreed by the other;
    -- DisputedBy means the other player says it is wrong. Both are for
    -- the organizer to see - an unconfirmed result still counts, because
    -- withholding the standings would give any sore loser a veto.
    "ConfirmedBy" integer,
    "ConfirmedAt" timestamp without time zone,
    "DisputedBy" integer,
    "DisputedAt" timestamp without time zone,
    "DisputeNote" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_TournamentMatches" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TournamentMatches_Tournaments" FOREIGN KEY ("TournamentId")
        REFERENCES public."Tournaments" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentMatches_Player1" FOREIGN KEY ("Player1Id")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentMatches_Player2" FOREIGN KEY ("Player2Id")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentMatches_ConfirmedBy" FOREIGN KEY ("ConfirmedBy")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT "FK_TournamentMatches_DisputedBy" FOREIGN KEY ("DisputedBy")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_TournamentMatches_Tournament_Round"
    ON public."TournamentMatches" USING btree
    ("TournamentId" ASC NULLS LAST, "Round" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_TournamentMatches_Disputed"
    ON public."TournamentMatches" USING btree ("TournamentId" ASC NULLS LAST)
    TABLESPACE pg_default
    WHERE "DisputedBy" IS NOT NULL;
