-- Table: public."Friendships"
-- Friend requests and friendships (Phase 9). One row per relationship:
-- Status 'pending' means Requester asked Addressee; 'accepted' means
-- friends. Declines delete the row.

CREATE TABLE IF NOT EXISTS public."Friendships"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "RequesterId" integer NOT NULL,
    "AddresseeId" integer NOT NULL,
    "Status" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending',
    "CreatedAt" timestamp without time zone NOT NULL,
    "RespondedAt" timestamp without time zone,
    CONSTRAINT "PK_Friendships" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_Friendships_Pair" UNIQUE ("RequesterId", "AddresseeId"),
    CONSTRAINT "CK_Friendships_NotSelf" CHECK ("RequesterId" <> "AddresseeId"),
    CONSTRAINT "FK_Friendships_Requester" FOREIGN KEY ("RequesterId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Friendships_Addressee" FOREIGN KEY ("AddresseeId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_Friendships_Addressee"
    ON public."Friendships" USING btree
    ("AddresseeId" ASC NULLS LAST)
    TABLESPACE pg_default;
