-- Table: public."Clubs"
-- Player clubs for local scenes, stores, and teams-in-waiting (Phase 9).

CREATE TABLE IF NOT EXISTS public."Clubs"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "OwnerId" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Clubs" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_Clubs_Name" UNIQUE ("Name"),
    CONSTRAINT "FK_Clubs_Users_OwnerId" FOREIGN KEY ("OwnerId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;
