-- Table: public."ClubMembers"
-- Club membership; Role is 'owner' or 'member'.

CREATE TABLE IF NOT EXISTS public."ClubMembers"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ClubId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Role" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'member',
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ClubMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_ClubMembers_Club_User" UNIQUE ("ClubId", "UserId"),
    CONSTRAINT "FK_ClubMembers_Clubs" FOREIGN KEY ("ClubId")
        REFERENCES public."Clubs" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_ClubMembers_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_ClubMembers_UserId"
    ON public."ClubMembers" USING btree
    ("UserId" ASC NULLS LAST)
    TABLESPACE pg_default;
