-- Table: public."TournamentStaff"
-- Co-organizers / judges for an event: everything the organizer can do
-- except delete the event or manage staff.

CREATE TABLE IF NOT EXISTS public."TournamentStaff"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TournamentId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Role" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'judge',
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TournamentStaff" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_TournamentStaff_Tournament_User" UNIQUE ("TournamentId", "UserId"),
    CONSTRAINT "FK_TournamentStaff_Tournaments" FOREIGN KEY ("TournamentId")
        REFERENCES public."Tournaments" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentStaff_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;
