-- Table: public."Seasons"
-- One row per competitive season. The latest row (highest Id) is the current
-- season and its Id is the season number. Starting a new season soft-resets
-- every rating toward the baseline (see RatingService.startNewSeason).

CREATE TABLE IF NOT EXISTS public."Seasons"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "StartedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Seasons" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Seasons"
    OWNER to keyteki;
