-- Table: public."TournamentMatchGames"
-- Links auto-created lobby games (and their results) to the individual
-- series games of a tournament match. GameUuid is the lobby/engine game
-- id (Games.GameId); the unique (MatchId, GameNumber) pair makes
-- auto-reporting from GAMEWIN idempotent.

CREATE TABLE IF NOT EXISTS public."TournamentMatchGames"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TournamentId" integer NOT NULL,
    "MatchId" integer NOT NULL,
    "GameNumber" integer NOT NULL,
    "GameUuid" text COLLATE pg_catalog."default" NOT NULL,
    "WinnerId" integer,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TournamentMatchGames" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_TournamentMatchGames_Match_Number" UNIQUE ("MatchId", "GameNumber"),
    CONSTRAINT "FK_TournamentMatchGames_Tournaments" FOREIGN KEY ("TournamentId")
        REFERENCES public."Tournaments" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentMatchGames_Matches" FOREIGN KEY ("MatchId")
        REFERENCES public."TournamentMatches" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_TournamentMatchGames_GameUuid"
    ON public."TournamentMatchGames" USING btree
    ("GameUuid" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
