-- Table: public."TournamentPlayerDecks"
-- Triad deck pools (Phase 7): exactly three decks per player, slot
-- 1-3. Classic single-deck events use TournamentPlayers.DeckId
-- instead; this table only exists for multi-deck formats.

CREATE TABLE IF NOT EXISTS public."TournamentPlayerDecks"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TournamentId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "DeckId" integer NOT NULL,
    "Slot" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TournamentPlayerDecks" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_TournamentPlayerDecks_Slot" UNIQUE ("TournamentId", "UserId", "Slot"),
    CONSTRAINT "FK_TournamentPlayerDecks_Tournaments" FOREIGN KEY ("TournamentId")
        REFERENCES public."Tournaments" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentPlayerDecks_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TournamentPlayerDecks_Decks" FOREIGN KEY ("DeckId")
        REFERENCES public."Decks" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_TournamentPlayerDecks_Tournament"
    ON public."TournamentPlayerDecks" USING btree
    ("TournamentId" ASC NULLS LAST, "UserId" ASC NULLS LAST)
    TABLESPACE pg_default;
