-- Table: public."BugReports"
-- Beta feedback: player-submitted bug reports, read and resolved from
-- the admin panel. Reports outlive their author (SET NULL) so the
-- record of what was broken survives account deletion.

CREATE TABLE IF NOT EXISTS public."BugReports"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer,
    "Page" text COLLATE pg_catalog."default",
    "Body" text COLLATE pg_catalog."default" NOT NULL,
    "UserAgent" text COLLATE pg_catalog."default",
    "Status" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'open',
    "ResolvedBy" integer,
    "ResolvedAt" timestamp without time zone,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_BugReports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BugReports_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT "FK_BugReports_ResolvedBy" FOREIGN KEY ("ResolvedBy")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_BugReports_Status"
    ON public."BugReports" USING btree
    ("Status" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;
