-- In-app notifications and their per-category delivery preferences.
--
-- Tournaments and the asynchronous community features are only useful if
-- players are told something happened - round pairings in particular are
-- unusable without a ping. One row per delivered notification per recipient.
--
-- "Category" is both the event taxonomy and the opt-out unit (see
-- server/services/notifications/taxonomy.js, which is the authority on the
-- valid values). It is deliberately not an enum: adding a category must not
-- require a migration, and an unknown category read back from an older row
-- degrades to "shown, no email" rather than breaking the query.
--
-- "Data" carries whatever the renderer needs (tournament id, round number,
-- requesting username) so the notification does not have to re-query at read
-- time and does not go stale if the underlying row later changes.

CREATE TABLE IF NOT EXISTS public."Notifications"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "Category" text NOT NULL,
    "Title" text NOT NULL,
    "Body" text,
    "Url" text,
    "Data" jsonb,
    -- Idempotency handle: "round 3 of event 12 was paired for this player" is
    -- one notification however many times the pairing hook fires.
    "DedupeKey" text,
    "ReadAt" timestamp without time zone,
    "EmailedAt" timestamp without time zone,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

-- The unread badge and the notification list are both "this user, newest
-- first", which is exactly this index.
CREATE INDEX IF NOT EXISTS "IX_Notifications_UserId_Id"
    ON public."Notifications" ("UserId", "Id" DESC);

-- Partial: the unread count only ever looks at unread rows, and this keeps
-- the index small as read history accumulates.
CREATE INDEX IF NOT EXISTS "IX_Notifications_Unread"
    ON public."Notifications" ("UserId")
    WHERE "ReadAt" IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Notifications_DedupeKey"
    ON public."Notifications" ("UserId", "DedupeKey")
    WHERE "DedupeKey" IS NOT NULL;

-- Per-category delivery preferences. A missing row means "the category's
-- defaults apply" - opting in is never written, so defaults can change later
-- without having to distinguish "chose the default" from "never chose".
CREATE TABLE IF NOT EXISTS public."NotificationPreferences"
(
    "UserId" integer NOT NULL,
    "Category" text NOT NULL,
    "InApp" boolean NOT NULL DEFAULT true,
    "Email" boolean NOT NULL DEFAULT true,
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_NotificationPreferences" PRIMARY KEY ("UserId", "Category"),
    CONSTRAINT "FK_NotificationPreferences_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE
);
