-- In-person game tracking (N13): paper games on the same ladder.
--
-- Most KeyForge is still played across a table. The platform already knows
-- decks, Amber and clubs, so the only thing missing is a trustworthy way to
-- say "we played, here is what happened".
--
-- TRUST IS THE WHOLE DESIGN
--
-- An online game is witnessed by the engine. A paper game is witnessed by two
-- people who may disagree, and one of whom has an incentive to. So a report is
-- never a fact until both sides independently produce the same one:
--
--   * Each player files their own row in InPersonGameReports. Neither sees a
--     number the other has to match - they are asked what happened, not asked
--     to confirm.
--   * Two agreeing reports commit. Anything else marks the game 'disputed' and
--     tells both players; it never silently picks a winner, and it never
--     moves anyone's Amber.
--   * A player cannot file both reports: one row per reporter, enforced by a
--     unique index rather than by the service remembering to check.
--
-- WHY IT MATERIALIZES INTO Games
--
-- A confirmed paper game writes a real Games row and two GamePlayers rows,
-- and then goes through the ordinary rating path. That is deliberate: match
-- history, deck records, house statistics and the Elo engine all read Games,
-- and a parallel table would mean teaching every one of them about a second
-- kind of game - four places to forget. Games."Source" is the one thing that
-- distinguishes them, so anything that wants to exclude paper play can, and
-- everything that does not care needs no change at all.

ALTER TABLE public."Games"
    ADD COLUMN IF NOT EXISTS "Source" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'online';

CREATE TABLE IF NOT EXISTS public."InPersonGames"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CreatedById" integer NOT NULL,
    "Player1Id" integer NOT NULL,
    "Player2Id" integer NOT NULL,
    "ClubId" integer,
    "GameFormat" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'archon',
    -- 'pending' | 'confirmed' | 'disputed' | 'cancelled'
    "Status" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending',
    -- Set once the two reports agree and the Games row exists.
    "GameId" integer,
    -- Whether the committed game actually moved Amber, and if not, why. A
    -- player who reported a game and saw no rating change is owed an answer.
    "Rated" boolean NOT NULL DEFAULT false,
    "UnratedReason" text COLLATE pg_catalog."default",
    "PlayedAt" timestamp without time zone,
    "ConfirmedAt" timestamp without time zone,
    "DisputedAt" timestamp without time zone,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_InPersonGames" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InPersonGames_CreatedBy" FOREIGN KEY ("CreatedById")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_InPersonGames_Player1" FOREIGN KEY ("Player1Id")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_InPersonGames_Player2" FOREIGN KEY ("Player2Id")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_InPersonGames_Clubs" FOREIGN KEY ("ClubId")
        REFERENCES public."Clubs" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    -- The committed game is the paper game's record; losing it would leave a
    -- confirmed row pointing at nothing.
    CONSTRAINT "FK_InPersonGames_Games" FOREIGN KEY ("GameId")
        REFERENCES public."Games" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    -- A game against yourself is not a game.
    CONSTRAINT "CK_InPersonGames_DistinctPlayers" CHECK ("Player1Id" <> "Player2Id")
)

TABLESPACE pg_default;

-- Both "games I am waiting on" and "games at my club" are read by these.
CREATE INDEX IF NOT EXISTS "IX_InPersonGames_Player1"
    ON public."InPersonGames" USING btree
    ("Player1Id" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_InPersonGames_Player2"
    ON public."InPersonGames" USING btree
    ("Player2Id" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_InPersonGames_Club"
    ON public."InPersonGames" USING btree
    ("ClubId" ASC NULLS LAST, "Id" DESC NULLS LAST)
    WHERE "ClubId" IS NOT NULL;

CREATE TABLE IF NOT EXISTS public."InPersonGameReports"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "InPersonGameId" integer NOT NULL,
    "ReporterId" integer NOT NULL,
    "WinnerId" integer NOT NULL,
    -- Keys are reported, never inferred: they are a direct Elo input and
    -- "the winner had 3" is an assumption, not a result.
    "Player1Keys" integer NOT NULL,
    "Player2Keys" integer NOT NULL,
    "Player1DeckId" integer,
    "Player2DeckId" integer,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_InPersonGameReports" PRIMARY KEY ("Id"),
    -- One report per player: the thing that makes two-sided confirmation
    -- mean anything.
    CONSTRAINT "UQ_InPersonGameReports_Game_Reporter" UNIQUE ("InPersonGameId", "ReporterId"),
    CONSTRAINT "FK_InPersonGameReports_Game" FOREIGN KEY ("InPersonGameId")
        REFERENCES public."InPersonGames" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_InPersonGameReports_Reporter" FOREIGN KEY ("ReporterId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_InPersonGameReports_Player1Deck" FOREIGN KEY ("Player1DeckId")
        REFERENCES public."Decks" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT "FK_InPersonGameReports_Player2Deck" FOREIGN KEY ("Player2DeckId")
        REFERENCES public."Decks" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT "CK_InPersonGameReports_Keys" CHECK ("Player1Keys" >= 0 AND "Player2Keys" >= 0)
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_InPersonGameReports_Game"
    ON public."InPersonGameReports" USING btree
    ("InPersonGameId" ASC NULLS LAST)
    TABLESPACE pg_default;
