-- Moderation toolkit (N5).
--
-- The platform inherited an IP ban list and a Users."Disabled" flag, and has
-- a canModerateChat role that could not actually do anything: there was no
-- way for a player to REPORT anything, and no action between "leave them
-- alone" and "disable the account". Those are the two gaps this closes.
--
-- WHY THE CONTEXT IS SNAPSHOTTED
--
-- Reports."Context" stores a copy of what was reported - the message text,
-- the deck name, the club description - rather than only a foreign key to it.
-- The most common thing a bad actor does after being reported is delete the
-- evidence, and a report that reads "message #4213" after the message is gone
-- is not a report at all. The row still carries the id so a moderator can
-- follow it if the target survives; the snapshot is what makes the report
-- readable if it does not.
--
-- WHY ACTIONS ARE A LOG, NOT A STATE COLUMN
--
-- ModerationActions is append-only: a mute is a row with an expiry, not a
-- boolean on Users. That means "why am I muted, and until when" always has an
-- answer, an action can be revoked without erasing that it happened, and a
-- player's history is inspectable rather than being a single flag that lost
-- everything before it. Revoking sets RevokedAt rather than deleting, for the
-- same reason.
--
-- WHY THE AUDIT LOG DENORMALIZES THE ACTOR
--
-- ModerationAuditLog keeps the moderator's name as text alongside their id.
-- Accounts get deleted, and an audit trail that turns into a column of nulls
-- the moment a moderator leaves is not an audit trail. The id stays for
-- joining while the account exists; the name is what survives it.

CREATE TABLE IF NOT EXISTS public."Reports"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ReporterId" integer,
    -- 'player' | 'message' | 'deck' | 'club' | 'store' | 'inPersonGame'
    "TargetType" text COLLATE pg_catalog."default" NOT NULL,
    -- The row being reported, where there is one.
    "TargetId" integer,
    -- The account the report is ABOUT, which is what a moderator acts on.
    -- Separate from TargetId because reporting a deck is a report about its
    -- owner, and a moderator should not have to re-derive that.
    "TargetUserId" integer,
    "Reason" text COLLATE pg_catalog."default" NOT NULL,
    "Details" text COLLATE pg_catalog."default",
    -- Snapshot of the reported thing, captured at report time.
    "Context" jsonb,
    -- 'open' | 'claimed' | 'resolved' | 'dismissed'
    "Status" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'open',
    "ClaimedById" integer,
    "ClaimedAt" timestamp without time zone,
    "ResolvedById" integer,
    "ResolvedAt" timestamp without time zone,
    "Resolution" text COLLATE pg_catalog."default",
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Reports" PRIMARY KEY ("Id"),
    -- A report outlives the reporter's account: deleting an account must not
    -- quietly erase the complaints it made about other people.
    CONSTRAINT "FK_Reports_Reporter" FOREIGN KEY ("ReporterId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT "FK_Reports_TargetUser" FOREIGN KEY ("TargetUserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT "FK_Reports_ClaimedBy" FOREIGN KEY ("ClaimedById")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT "FK_Reports_ResolvedBy" FOREIGN KEY ("ResolvedById")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

-- The queue read: open work, oldest first.
CREATE INDEX IF NOT EXISTS "IX_Reports_Status"
    ON public."Reports" USING btree
    ("Status" ASC NULLS LAST, "Id" ASC NULLS LAST)
    TABLESPACE pg_default;

-- "What else has been reported about this player" - the question a moderator
-- asks before deciding how hard to act.
CREATE INDEX IF NOT EXISTS "IX_Reports_TargetUser"
    ON public."Reports" USING btree
    ("TargetUserId" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_Reports_Reporter"
    ON public."Reports" USING btree
    ("ReporterId" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."ModerationActions"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TargetUserId" integer NOT NULL,
    "ActorId" integer,
    -- 'note' | 'warn' | 'mute' | 'timeout' | 'ban'
    "Action" text COLLATE pg_catalog."default" NOT NULL,
    "Reason" text COLLATE pg_catalog."default" NOT NULL,
    -- NULL means indefinite. Every restriction carries an expiry the player
    -- can be told, because "you are muted" without a duration is a worse
    -- punishment than the one the moderator chose.
    "ExpiresAt" timestamp without time zone,
    "ReportId" integer,
    "RevokedById" integer,
    "RevokedAt" timestamp without time zone,
    "RevokeReason" text COLLATE pg_catalog."default",
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ModerationActions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ModerationActions_Target" FOREIGN KEY ("TargetUserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_ModerationActions_Actor" FOREIGN KEY ("ActorId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT "FK_ModerationActions_RevokedBy" FOREIGN KEY ("RevokedById")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    -- The report a sanction came from survives the sanction being revoked.
    CONSTRAINT "FK_ModerationActions_Report" FOREIGN KEY ("ReportId")
        REFERENCES public."Reports" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

-- The hot path: "is this player restricted right now", asked on every chat
-- message. Partial on live rows only, since revoked ones are history.
CREATE INDEX IF NOT EXISTS "IX_ModerationActions_Active"
    ON public."ModerationActions" USING btree
    ("TargetUserId" ASC NULLS LAST, "Action" ASC NULLS LAST)
    TABLESPACE pg_default
    WHERE "RevokedAt" IS NULL;

CREATE INDEX IF NOT EXISTS "IX_ModerationActions_Target"
    ON public."ModerationActions" USING btree
    ("TargetUserId" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."ModerationAuditLog"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 CACHE 1 ),
    "ActorId" integer,
    -- Kept as text so the trail survives the account being deleted.
    "ActorName" text COLLATE pg_catalog."default",
    "Action" text COLLATE pg_catalog."default" NOT NULL,
    "TargetType" text COLLATE pg_catalog."default",
    "TargetId" integer,
    "TargetName" text COLLATE pg_catalog."default",
    "Detail" jsonb,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ModerationAuditLog" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ModerationAuditLog_Actor" FOREIGN KEY ("ActorId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_ModerationAuditLog_CreatedAt"
    ON public."ModerationAuditLog" USING btree
    ("CreatedAt" DESC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_ModerationAuditLog_Target"
    ON public."ModerationAuditLog" USING btree
    ("TargetType" ASC NULLS LAST, "TargetId" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;

-- ARCHON (N13): a disputed paper game can now be escalated to the moderation
-- queue instead of only being settled by the two players re-reporting.
ALTER TABLE public."InPersonGames"
    ADD COLUMN IF NOT EXISTS "ReportId" integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_InPersonGames_Reports'
    ) THEN
        ALTER TABLE public."InPersonGames"
            ADD CONSTRAINT "FK_InPersonGames_Reports" FOREIGN KEY ("ReportId")
            REFERENCES public."Reports" ("Id") MATCH SIMPLE
            ON UPDATE NO ACTION
            ON DELETE SET NULL;
    END IF;
END $$;
