-- ARCHON (N14): capturing a request for the iOS TestFlight beta.
--
-- The Expo app already has real testers - the owner has invited friends by
-- hand - so nothing here talks to Apple. Apple caps how many external testers
-- a TestFlight can hold and enrollment stays entirely manual in App Store
-- Connect; what this table adds is a queue so a request does not have to
-- arrive over chat. An admin works through "Status" = 'pending' rows in the
-- order they came in and marks each one resolved once the invite (or a
-- decline) has actually been sent outside this system.
--
-- One open request per account: a player who already has a pending request
-- and asks again should see their existing request, not create a second row
-- an admin has to notice is a duplicate. The partial unique index enforces
-- that only while a request is still pending, so someone who was resolved
-- (invited, or the request lapsed) can ask again later - e.g. after
-- reinstalling or losing the original invite email.
CREATE TABLE IF NOT EXISTS public."TestFlightRequests"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    -- The Apple ID email Apple sends the TestFlight invite to. Deliberately
    -- separate from the account's own email - most players' Apple ID is a
    -- different address, and guessing wrong wastes one of Apple's limited
    -- external-tester slots on an invite nobody can accept.
    "AppleIdEmail" text COLLATE pg_catalog."default" NOT NULL,
    -- 'pending' | 'resolved'. An inbox, not a ticketing system - matching
    -- BugReports: what happened (invited vs. declined) is worth a word in an
    -- admin note somewhere else if it matters, not a status enum here.
    "Status" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending',
    "ResolvedBy" integer,
    "ResolvedAt" timestamp without time zone,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT "PK_TestFlightRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TestFlightRequests_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_TestFlightRequests_Users_ResolvedBy" FOREIGN KEY ("ResolvedBy")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

CREATE UNIQUE INDEX IF NOT EXISTS "UX_TestFlightRequests_UserId_Pending"
    ON public."TestFlightRequests" USING btree
    ("UserId" ASC)
    TABLESPACE pg_default
    WHERE "Status" = 'pending';

-- What the admin queue reads: pending requests, oldest first.
CREATE INDEX IF NOT EXISTS "IX_TestFlightRequests_Status"
    ON public."TestFlightRequests" USING btree
    ("Status" ASC NULLS LAST, "Id" ASC NULLS LAST)
    TABLESPACE pg_default;
