-- ARCHON (N18): the Proving Grounds - Vault Master's background deck testing.
--
-- A computer plays a member's enrolled decks against each other, a few games
-- an hour, and these tables hold what it found: who was in each sparring
-- match, who won, and enough of the shape of the game (keys, turns, house
-- calls, who went first) to say something useful about *how* the deck wins.
--
-- WHY THIS IS NOT A "Games" ROW
--
-- Every consumer of "Games" - deck records, house statistics, the meta
-- dashboard, leaderboard win counts, the Tournament Lab - filters on nothing
-- but "FinishedAt IS NOT NULL AND WinnerId IS NOT NULL". A simulated game
-- written there would be a real result everywhere at once, and keeping it out
-- would mean teaching some thirty queries about a new kind of game and never
-- missing one. A table nothing else reads cannot leak into a statistic by
-- accident, which is the property the whole feature stands on: the Proving
-- Grounds must never move Amber, a deck record, or a leaderboard.
-- (RatingService is trigger-driven from the game router, so it never sees
-- these rows either - nothing here calls processGame.)
--
-- WHY THE ROSTER IS ITS OWN TABLE
--
-- Enrollment is a standing instruction ("keep playing this deck"), not an
-- event. Deriving it from the games table would make "stop testing this
-- deck" impossible to say without deleting history, and the history is the
-- product.

CREATE TABLE IF NOT EXISTS public."ProvingGroundsDecks"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "DeckId" integer NOT NULL,
    "EnrolledAt" timestamp without time zone NOT NULL,
    -- ARCHON (N21): randomizer slots - chosen by the randomizer, swapped for
    -- a fresh random deck once this one has played its target.
    "Random" boolean NOT NULL DEFAULT false,
    "RandomGamesTarget" integer,
    CONSTRAINT "PK_ProvingGroundsDecks" PRIMARY KEY ("Id"),
    -- CASCADE both ways: an enrollment is meaningless without its account or
    -- its deck. Results (below) survive deck changes independently.
    CONSTRAINT "FK_ProvingGroundsDecks_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_ProvingGroundsDecks_Decks" FOREIGN KEY ("DeckId")
        REFERENCES public."Decks" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

-- A deck is on a member's roster once. Enforced here rather than in the
-- service because "is it already enrolled" followed by "then enroll it" is
-- two statements, and two requests can pass the first simultaneously.
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProvingGroundsDecks_UserDeck"
    ON public."ProvingGroundsDecks" ("UserId", "DeckId");

CREATE TABLE IF NOT EXISTS public."ProvingGroundsGames"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    -- The roster the game was played for. Both decks belong to this account;
    -- sparring never crosses accounts, so one column says whose lab this is.
    "UserId" integer NOT NULL,
    "WinnerDeckId" integer NOT NULL,
    "LoserDeckId" integer NOT NULL,
    "WinnerKeys" smallint NOT NULL,
    "LoserKeys" smallint NOT NULL,
    "Turns" smallint NOT NULL,
    -- Whether the winner took the first turn, so first-player advantage in
    -- the lab can be reported rather than guessed at.
    "WinnerWentFirst" boolean NOT NULL,
    -- The house each side called on its first turn, and how often each house
    -- was called across the game. This is what "which opening actually wins
    -- with this deck" is computed from. Houses are stored by code
    -- ('brobnar'), the same strings the engine and DeckHouses use.
    "WinnerFirstHouse" text COLLATE pg_catalog."default",
    "LoserFirstHouse" text COLLATE pg_catalog."default",
    "WinnerHouseCalls" jsonb,
    "LoserHouseCalls" jsonb,
    -- Wall-clock cost of the simulation, kept so the lab's own overhead can
    -- be watched from the data it produces.
    "DurationMs" integer,
    -- ARCHON (N21): showcase games - played by the deep planner, carrying
    -- its per-decision annotations.
    "Deep" boolean NOT NULL DEFAULT false,
    "Annotations" jsonb,
    -- ARCHON (N28): which of the three sparring pilots played this game (both
    -- seats - a shared pilot is what keeps the result attributable to the decks).
    -- NULL for a game played before the personas existed, and for showcase games,
    -- which are played by the champion unstyled. See labPersonas.js.
    "Persona" text COLLATE pg_catalog."default",
    "FinishedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ProvingGroundsGames" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProvingGroundsGames_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    -- CASCADE with the deck: a result for a deck that no longer exists is
    -- unreadable (there is nothing to name it by), and deck deletion on this
    -- platform already archives the *official* record separately.
    CONSTRAINT "FK_ProvingGroundsGames_WinnerDecks" FOREIGN KEY ("WinnerDeckId")
        REFERENCES public."Decks" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_ProvingGroundsGames_LoserDecks" FOREIGN KEY ("LoserDeckId")
        REFERENCES public."Decks" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

-- The page reads one member's lab newest-first; the sweep counts one
-- member's games since UTC midnight. Both are this index.
CREATE INDEX IF NOT EXISTS "IX_ProvingGroundsGames_User_FinishedAt"
    ON public."ProvingGroundsGames" USING btree
    ("UserId" ASC NULLS LAST, "FinishedAt" DESC NULLS LAST)
    TABLESPACE pg_default;

-- Per-deck aggregates read by either side of the result.
CREATE INDEX IF NOT EXISTS "IX_ProvingGroundsGames_Winner"
    ON public."ProvingGroundsGames" ("WinnerDeckId");

CREATE INDEX IF NOT EXISTS "IX_ProvingGroundsGames_Loser"
    ON public."ProvingGroundsGames" ("LoserDeckId");
