-- Table: public."DeckShares"
--
-- ARCHON: lend a deck to a friend.
--
-- One physical KeyForge deck, played by more than one person, is ordinary - and
-- since the shared-deck labels were turned off it is allowed here. This makes it
-- deliberate rather than something two people arrange by pasting a Master Vault
-- link at each other: you offer the deck to a friend, they accept, and a copy
-- appears in their collection marked as yours.
--
-- Nothing enters anybody's collection without their say-so, which is why this is
-- an offer with a status rather than a write into someone else's decks.
--
-- Mirrors migration 72.

CREATE TABLE IF NOT EXISTS public."DeckShares"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DeckId" integer NOT NULL,
    "FromUserId" integer NOT NULL,
    "ToUserId" integer NOT NULL,
    -- 'pending' | 'accepted' | 'declined' | 'revoked'
    "Status" text NOT NULL DEFAULT 'pending',
    "AcceptedDeckId" integer,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "RespondedAt" timestamp without time zone,
    CONSTRAINT "PK_DeckShares" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_DeckShares_NotSelf" CHECK ("FromUserId" <> "ToUserId"),
    CONSTRAINT "CK_DeckShares_Status" CHECK (
        "Status" IN ('pending', 'accepted', 'declined', 'revoked')
    ),
    CONSTRAINT "FK_DeckShares_Deck" FOREIGN KEY ("DeckId")
        REFERENCES public."Decks" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DeckShares_AcceptedDeck" FOREIGN KEY ("AcceptedDeckId")
        REFERENCES public."Decks" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_DeckShares_From" FOREIGN KEY ("FromUserId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DeckShares_To" FOREIGN KEY ("ToUserId")
        REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

-- One live offer per deck per friend. Partial, so the same deck can be offered
-- again after a decline or a revoke - which is the point of declining rather
-- than blocking.
CREATE UNIQUE INDEX IF NOT EXISTS "UQ_DeckShares_Pending"
    ON public."DeckShares" ("DeckId", "ToUserId")
    WHERE "Status" = 'pending';

CREATE INDEX IF NOT EXISTS "IX_DeckShares_ToUserId" ON public."DeckShares" ("ToUserId");
CREATE INDEX IF NOT EXISTS "IX_DeckShares_FromUserId" ON public."DeckShares" ("FromUserId");

-- ARCHON: who lent this deck. On the recipient's copy, not the original.
ALTER TABLE public."Decks"
    ADD COLUMN IF NOT EXISTS "SharedFromUserId" integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_Decks_SharedFrom'
    ) THEN
        ALTER TABLE public."Decks"
            ADD CONSTRAINT "FK_Decks_SharedFrom" FOREIGN KEY ("SharedFromUserId")
            REFERENCES public."Users" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_Decks_SharedFromUserId"
    ON public."Decks" ("SharedFromUserId")
    WHERE "SharedFromUserId" IS NOT NULL;
