-- ARCHON (N21): the learning bot - its policies and its training diary.
--
-- "BotPolicies" holds every brain the sparring partner has ever had: the
-- model itself as one JSON document (weights plus per-card weights - small
-- enough that a row IS the deployment), its lineage, and its arena record.
-- Exactly one row is 'champion' at a time; a 'candidate' earns its place by
-- beating the champion over enough games that the Wilson bound clears 50%,
-- and a beaten candidate retires with its record kept. Promotion is a
-- status flip, rollback is the same flip backwards - no redeploy touches a
-- model.
--
-- "BotTrainingGames" is the diary: one row per logged sparring game, the
-- decisions it contained (features, by side) and who won, which is all
-- supervised learning needs. It is a working set, not an archive - the
-- sweep prunes it to a configured depth, newest kept.
--
CREATE TABLE IF NOT EXISTS public."BotPolicies"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Version" integer NOT NULL,
    -- 'candidate' | 'champion' | 'retired'
    "Status" text COLLATE pg_catalog."default" NOT NULL,
    "Model" jsonb NOT NULL,
    "TrainedGames" integer NOT NULL DEFAULT 0,
    "ArenaWins" integer NOT NULL DEFAULT 0,
    "ArenaLosses" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp without time zone NOT NULL,
    "PromotedAt" timestamp without time zone,
    CONSTRAINT "PK_BotPolicies" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_BotPolicies_Version" UNIQUE ("Version")
)

TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."BotTrainingGames"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    -- The champion whose play produced this game, for lineage. NULL for the
    -- heuristic bot's games - version zero of the species.
    "PolicyVersion" integer,
    -- 'challenger-alpha' | 'challenger-omega'
    "WinnerSide" text COLLATE pg_catalog."default" NOT NULL,
    "Decisions" jsonb NOT NULL,
    -- ARCHON (N28): the persona that piloted this game, when one did. The rows
    -- are still valid training data - labels come from outcomes and search, not
    -- from the behaviour that produced them - but "how much of my diary is one
    -- style" should have an answer. See labPersonas.js.
    "Persona" text COLLATE pg_catalog."default",
    -- ARCHON (N45): where this game came from. 'self' is the lab sparring
    -- against itself, which is every row the loop wrote before this existed
    -- and so is the default; 'human' is a game a person played on this site,
    -- captured live at the game node. The distinction has to survive into the
    -- table because it decides how hard the row pulls at training time, and
    -- the pull is an admin knob - a diary that had baked the weight in at
    -- capture time could never be re-weighted. See humanLearning.js.
    "Source" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'self',
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_BotTrainingGames" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

-- The trainer fetches newest-first and the pruner deletes oldest-first;
-- both are this index.
CREATE INDEX IF NOT EXISTS "IX_BotTrainingGames_Id"
    ON public."BotTrainingGames" USING btree
    ("Id" DESC NULLS LAST)
    TABLESPACE pg_default;

-- ARCHON (N28): the persona ladder - the three sparring pilots' records against
-- each other.
--
-- A persona is the champion model pulled away from the policy trained to win, so
-- each is slightly the weaker player for it; one pulled too far is simply a bad
-- player, and a deck's spread across the three would then measure which decks
-- punish bad play. Ordinary sparring cannot show that, because both seats share
-- one pilot by design - that is what keeps a game's result attributable to the
-- decks - so the personas duel each other on neutral decks with paired seeds,
-- the same way a candidate meets the champion.
--
-- One row per unordered pair, keys sorted so a pair is one record.
CREATE TABLE IF NOT EXISTS public."ChallengePersonaDuels"
(
    "PersonaA" text COLLATE pg_catalog."default" NOT NULL,
    "PersonaB" text COLLATE pg_catalog."default" NOT NULL,
    "WinsA" integer NOT NULL DEFAULT 0,
    "WinsB" integer NOT NULL DEFAULT 0,
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ChallengePersonaDuels" PRIMARY KEY ("PersonaA", "PersonaB")
)

TABLESPACE pg_default;
