-- ARCHON (N14): self-serve TestFlight requests, worked in order from
-- /admin/ios-beta-requests. See migrations/91 for the full rationale.

CREATE TABLE IF NOT EXISTS public."IosBetaRequests"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer,
    "AppleId" text COLLATE pg_catalog."default" NOT NULL,
    "Status" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending',
    "ClearedBy" integer,
    "ClearedAt" timestamp without time zone,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_IosBetaRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IosBetaRequests_Users" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT "FK_IosBetaRequests_ClearedBy" FOREIGN KEY ("ClearedBy")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_IosBetaRequests_Status"
    ON public."IosBetaRequests" USING btree
    ("Status" ASC NULLS LAST, "Id" DESC NULLS LAST)
    TABLESPACE pg_default;

CREATE UNIQUE INDEX IF NOT EXISTS "UX_IosBetaRequests_UserId_Pending"
    ON public."IosBetaRequests" USING btree ("UserId")
    TABLESPACE pg_default
    WHERE "Status" = 'pending' AND "UserId" IS NOT NULL;
