-- Direct messages between two players.
--
-- WHY
--
-- A tournament pairs two people who have to agree on when to play, and the
-- platform gave them a scheduler and no way to talk. "Can we do 8 instead of
-- 7?" went to Discord, or to the event chat everybody reads, or nowhere. The
-- scheduler proposes and accepts; this is the conversation around it.
--
-- WHY ONE TABLE AND NO CONVERSATION ROW
--
-- A conversation is the pair of people in it. (LEAST, GREATEST) of the two ids
-- names it, so the inbox is one grouped query and nothing has to be created
-- before the first message is sent. A "Conversations" table would only ever
-- have mirrored what this one already says.
--
-- WHY "ReadAt" IS PER MESSAGE
--
-- The unread badge is "how many messages are waiting for me", and opening a
-- thread marks that sender's messages read in one update. A per-conversation
-- cursor would need a row per pair per user and would have to be created on
-- first read; a per-message stamp needs neither, and the partial index below
-- keeps the count cheap however long the history gets.
--
-- WHY "MatchId"
--
-- Most of these will be about a match. Recording which one lets the thread say
-- "about your round 2 match" and lets a moderator reading a report see the
-- context. SET NULL on delete: the message outlives the event it was about.
--
-- Text is filtered at the point of sending with the same content filter as
-- lobby chat, and the block list is honoured in both directions before a row
-- is written - a blocked player cannot message and cannot be messaged.

CREATE TABLE IF NOT EXISTS public."DirectMessages"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "SenderId" integer NOT NULL,
    "RecipientId" integer NOT NULL,
    "Text" text COLLATE pg_catalog."default" NOT NULL,
    "MatchId" integer,
    "SentAt" timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "ReadAt" timestamp without time zone,
    CONSTRAINT "PK_DirectMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_DirectMessages_NotSelf" CHECK ("SenderId" <> "RecipientId"),
    CONSTRAINT "FK_DirectMessages_Sender" FOREIGN KEY ("SenderId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_DirectMessages_Recipient" FOREIGN KEY ("RecipientId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_DirectMessages_Match" FOREIGN KEY ("MatchId")
        REFERENCES public."TournamentMatches" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

-- The thread between two people, in order. LEAST/GREATEST so the same index
-- serves whichever of the pair is asking.
CREATE INDEX IF NOT EXISTS "IX_DirectMessages_Pair"
    ON public."DirectMessages" USING btree
    (LEAST("SenderId", "RecipientId"), GREATEST("SenderId", "RecipientId"), "Id");

-- The unread badge: what is waiting for me. Partial, because read history is
-- most of the table and the count never looks at it.
CREATE INDEX IF NOT EXISTS "IX_DirectMessages_Unread"
    ON public."DirectMessages" USING btree ("RecipientId")
    WHERE "ReadAt" IS NULL;
