/**
 * Country -> competitive region mapping for rankings (Phase 6).
 *
 * Regions are deliberately coarse (5 buckets) so every leaderboard has
 * enough players to be meaningful. The mapping is code-defined for now;
 * the admin settings service can make region definitions editable later
 * (ROADMAP: admin-config region definitions).
 *
 * Countries are ISO 3166-1 alpha-2 codes.
 */
const REGIONS = {
    NA: ['US', 'CA', 'MX', 'BM', 'GL', 'PM'],
    LATAM: [
        'AR',
        'BO',
        'BR',
        'BZ',
        'CL',
        'CO',
        'CR',
        'CU',
        'DO',
        'EC',
        'GT',
        'GY',
        'HN',
        'HT',
        'JM',
        'NI',
        'PA',
        'PE',
        'PR',
        'PY',
        'SR',
        'SV',
        'TT',
        'UY',
        'VE',
        'AG',
        'AW',
        'BB',
        'BS',
        'DM',
        'GD',
        'KN',
        'LC',
        'VC',
        'AI',
        'KY',
        'MQ',
        'GP',
        'GF',
        'VG',
        'VI',
        'TC',
        'MS',
        'BQ',
        'CW',
        'SX'
    ],
    EU: [
        'AD',
        'AL',
        'AT',
        'BA',
        'BE',
        'BG',
        'BY',
        'CH',
        'CY',
        'CZ',
        'DE',
        'DK',
        'EE',
        'ES',
        'FI',
        'FO',
        'FR',
        'GB',
        'GG',
        'GI',
        'GR',
        'HR',
        'HU',
        'IE',
        'IM',
        'IS',
        'IT',
        'JE',
        'LI',
        'LT',
        'LU',
        'LV',
        'MC',
        'MD',
        'ME',
        'MK',
        'MT',
        'NL',
        'NO',
        'PL',
        'PT',
        'RO',
        'RS',
        'RU',
        'SE',
        'SI',
        'SK',
        'SM',
        'UA',
        'VA',
        'XK',
        'AX'
    ],
    MEA: [
        'AE',
        'AM',
        'AO',
        'AZ',
        'BF',
        'BH',
        'BI',
        'BJ',
        'BW',
        'CD',
        'CF',
        'CG',
        'CI',
        'CM',
        'CV',
        'DJ',
        'DZ',
        'EG',
        'ER',
        'ET',
        'GA',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GW',
        'IL',
        'IQ',
        'IR',
        'JO',
        'KE',
        'KM',
        'KW',
        'LB',
        'LR',
        'LS',
        'LY',
        'MA',
        'MG',
        'ML',
        'MR',
        'MU',
        'MW',
        'MZ',
        'NA',
        'NE',
        'NG',
        'OM',
        'PS',
        'QA',
        'RE',
        'RW',
        'SA',
        'SC',
        'SD',
        'SL',
        'SN',
        'SO',
        'SS',
        'ST',
        'SY',
        'SZ',
        'TD',
        'TG',
        'TN',
        'TR',
        'TZ',
        'UG',
        'YE',
        'YT',
        'ZA',
        'ZM',
        'ZW',
        'EH'
    ],
    APAC: [
        'AF',
        'AU',
        'BD',
        'BN',
        'BT',
        'CC',
        'CK',
        'CN',
        'CX',
        'FJ',
        'FM',
        'GU',
        'HK',
        'ID',
        'IN',
        'JP',
        'KG',
        'KH',
        'KI',
        'KP',
        'KR',
        'KZ',
        'LA',
        'LK',
        'MH',
        'MM',
        'MN',
        'MO',
        'MP',
        'MV',
        'MY',
        'NC',
        'NF',
        'NP',
        'NR',
        'NU',
        'NZ',
        'PF',
        'PG',
        'PH',
        'PK',
        'PW',
        'SB',
        'SG',
        'TH',
        'TJ',
        'TK',
        'TL',
        'TM',
        'TO',
        'TV',
        'TW',
        'UZ',
        'VN',
        'VU',
        'WF',
        'WS',
        'AS'
    ]
};

const COUNTRY_TO_REGION = {};
for (const [region, countries] of Object.entries(REGIONS)) {
    for (const country of countries) {
        COUNTRY_TO_REGION[country] = region;
    }
}

const isValidCountry = (code) => typeof code === 'string' && !!COUNTRY_TO_REGION[code];

const regionForCountry = (code) => COUNTRY_TO_REGION[code] || null;

const countriesInRegion = (region) => REGIONS[region] || [];

const REGION_NAMES = Object.keys(REGIONS);

module.exports = {
    REGIONS,
    REGION_NAMES,
    isValidCountry,
    regionForCountry,
    countriesInRegion
};
