const fs = require('fs');
const path = require('path');

const logger = require('../../log');

/**
 * ARCHON (N43): AERC-style card traits - what KIND of good a card is.
 *
 * The card priors (N38) gave every card one number: how good. These give it
 * a direction, on the axes Decks of KeyForge's AERC system proved out over
 * years of hand curation: expected amber, amber control, creature control,
 * artifact control, efficiency, disruption. The TAXONOMY is DoK's - it is
 * the field's shared vocabulary for what a KeyForge card does - while the
 * SCORES are this platform's own, generated by the same one-time card
 * reading job that produced the priors (scripts/generate-card-traits.js).
 * DoK's own curated numbers stay theirs: their site's code is AGPL and
 * their ratings live in their database, so we borrow the framework and do
 * our own homework in it.
 *
 * Why the model wants graded axes when it already has role crosses (F3):
 * roles are binary and coarse - "this card steals" - while an axis says HOW
 * MUCH, on a shared scale. A shared `card:ax:creatureControl` weight is one
 * number that generalizes across every card that answers creatures, learned
 * from all of them together; per-card weights need ~20 sightings of each
 * card separately to say less.
 *
 * Same contract as the priors: the file ships committed, runtime needs no
 * API, a server without the file simply emits no axis features, and every
 * key is add-only.
 */

const TRAITS_FILE = path.join(__dirname, 'data', 'cardTraits.json');

/** The axes, in DoK's names. Scores are 0-4; features scale to [0, 1]. */
const AXES = [
    'expectedAmber',
    'amberControl',
    'creatureControl',
    'artifactControl',
    'efficiency',
    'disruption'
];

const SCALE = 4;

/** Raw file cache: { file, scores|null }. Absence is cached too. */
let loaded = null;

/** Scaled per-card cache, keyed by file. */
let mapped = null;

function traitScores(file = TRAITS_FILE) {
    if (!loaded || loaded.file !== file) {
        let scores = null;

        try {
            if (fs.existsSync(file)) {
                const parsed = JSON.parse(fs.readFileSync(file, 'utf8'));

                if (parsed && parsed.scores && typeof parsed.scores === 'object') {
                    scores = parsed.scores;
                }
            }
        } catch (err) {
            logger.error('Card traits: could not read the traits file', err);
        }

        loaded = { file, scores };
    }

    return loaded.scores;
}

/**
 * One card's axes, scaled to [0, 1], zeros omitted (the features' sparse
 * convention: absent reads the same to the model and keeps records small).
 * Null when the card is unknown or the file is absent.
 */
function traitsFor(cardId, file = TRAITS_FILE) {
    if (!cardId) {
        return null;
    }

    if (!mapped || mapped.file !== file) {
        mapped = { file, cards: new Map() };
    }

    if (mapped.cards.has(cardId)) {
        return mapped.cards.get(cardId);
    }

    const scores = traitScores(file);
    const raw = scores && scores[cardId];
    let traits = null;

    if (raw && typeof raw === 'object') {
        for (const axis of AXES) {
            const value = Number(raw[axis]);

            if (Number.isFinite(value) && value > 0) {
                traits = traits || {};
                traits[axis] = Math.min(1, Math.max(0, value) / SCALE);
            }
        }
    }

    mapped.cards.set(cardId, traits);

    return traits;
}

/** For tests: drop the caches so a spec can point at its own file. */
function resetCache() {
    loaded = null;
    mapped = null;
}

module.exports = { TRAITS_FILE, AXES, SCALE, traitScores, traitsFor, resetCache };
