const fs = require('fs');
const path = require('path');

const logger = require('../../log');

/**
 * ARCHON (N43): AERC-style card traits - what KIND of good a card is.
 *
 * The card priors (N38) gave every card one number: how good. These give it
 * a direction, on the axes Decks of KeyForge's AERC system proved out over
 * years of hand curation: expected amber, amber control, creature control,
 * artifact control, efficiency, disruption. The TAXONOMY is DoK's - it is
 * the field's shared vocabulary for what a KeyForge card does - while the
 * SCORES are this platform's own, generated by the same one-time card
 * reading job that produced the priors (scripts/generate-card-traits.js).
 * DoK's own curated numbers stay theirs: their site's code is AGPL and
 * their ratings live in their database, so we borrow the framework and do
 * our own homework in it.
 *
 * Why the model wants graded axes when it already has role crosses (F3):
 * roles are binary and coarse - "this card steals" - while an axis says HOW
 * MUCH, on a shared scale. A shared `card:ax:creatureControl` weight is one
 * number that generalizes across every card that answers creatures, learned
 * from all of them together; per-card weights need ~20 sightings of each
 * card separately to say less.
 *
 * Same contract as the priors: the file ships committed, runtime needs no
 * API, a server without the file simply emits no axis features, and every
 * key is add-only.
 */

const TRAITS_FILE = path.join(__dirname, 'data', 'cardTraits.json');

/** The axes, in DoK's names. Scores are 0-4; features scale to [0, 1]. */
const AXES = [
    'expectedAmber',
    'amberControl',
    'creatureControl',
    'artifactControl',
    'efficiency',
    'disruption'
];

const SCALE = 4;

/**
 * ARCHON (N43): the synergy vocabulary - the mechanics one card can PROVIDE
 * and another can WANT. DoK models this per card as provides/wants lists
 * (their SynTraitValue system); this is the same idea in a deliberately
 * coarse, set-agnostic vocabulary. A payoff card `wants: ['capture']`; an
 * enabler `provides: ['capture']`; the features in labFeatures light up when
 * a candidate's wants are satisfied by the board (cash it in) or only by the
 * hand (the partner has not landed yet - sequencing, learnable).
 */
const SYNERGY_TAGS = [
    'capture', // puts amber onto friendly creatures
    'archives', // puts cards into the archives
    'damage', // spreads damage among enemy creatures
    'swarm', // floods multiple or token creatures into play
    'friendlyDiscard', // discards from its owner's own hand or deck
    'friendlyDestroy', // destroys or sacrifices friendly creatures on purpose
    'powerBoost', // raises friendly creature power
    'bigCreature' // supplies a high-power body (power 6+)
];

/** Raw file cache: { file, scores|null }. Absence is cached too. */
let loaded = null;

/** Scaled per-card cache, keyed by file. */
let mapped = null;

function traitScores(file = TRAITS_FILE) {
    if (!loaded || loaded.file !== file) {
        let scores = null;

        try {
            if (fs.existsSync(file)) {
                const parsed = JSON.parse(fs.readFileSync(file, 'utf8'));

                if (parsed && parsed.scores && typeof parsed.scores === 'object') {
                    scores = parsed.scores;
                }
            }
        } catch (err) {
            logger.error('Card traits: could not read the traits file', err);
        }

        loaded = { file, scores };
    }

    return loaded.scores;
}

/**
 * One card's axes, scaled to [0, 1], zeros omitted (the features' sparse
 * convention: absent reads the same to the model and keeps records small).
 * Null when the card is unknown or the file is absent.
 */
function traitsFor(cardId, file = TRAITS_FILE) {
    if (!cardId) {
        return null;
    }

    if (!mapped || mapped.file !== file) {
        mapped = { file, cards: new Map() };
    }

    if (mapped.cards.has(cardId)) {
        return mapped.cards.get(cardId);
    }

    const scores = traitScores(file);
    const raw = scores && scores[cardId];
    let traits = null;

    if (raw && typeof raw === 'object') {
        for (const axis of AXES) {
            const value = Number(raw[axis]);

            if (Number.isFinite(value) && value > 0) {
                traits = traits || {};
                traits[axis] = Math.min(1, Math.max(0, value) / SCALE);
            }
        }
    }

    mapped.cards.set(cardId, traits);

    return traits;
}

/** Per-card synergy cache, keyed by file. */
let synergyCache = null;

/**
 * One card's synergy lists - `{ provides, wants }`, each an array of known
 * SYNERGY_TAGS - or null for a card with neither (the overwhelmingly common
 * case), an unknown card, or an absent file. Unknown tags in the file are
 * dropped rather than trusted: the vocabulary is a contract with the
 * features, and a stray string must not become a phantom mechanic.
 */
function synergiesFor(cardId, file = TRAITS_FILE) {
    if (!cardId) {
        return null;
    }

    if (!synergyCache || synergyCache.file !== file) {
        synergyCache = { file, cards: new Map() };
    }

    if (synergyCache.cards.has(cardId)) {
        return synergyCache.cards.get(cardId);
    }

    const scores = traitScores(file);
    const raw = scores && scores[cardId];
    const clean = (list) =>
        Array.isArray(list) ? list.filter((tag) => SYNERGY_TAGS.includes(tag)) : [];
    let synergy = null;

    if (raw && typeof raw === 'object') {
        const provides = clean(raw.provides);
        const wants = clean(raw.wants);

        if (provides.length || wants.length) {
            synergy = { provides, wants };
        }
    }

    synergyCache.cards.set(cardId, synergy);

    return synergy;
}

/** For tests: drop the caches so a spec can point at its own file. */
function resetCache() {
    loaded = null;
    mapped = null;
    synergyCache = null;
}

module.exports = {
    TRAITS_FILE,
    AXES,
    SCALE,
    SYNERGY_TAGS,
    traitScores,
    traitsFor,
    synergiesFor,
    resetCache
};
